#ifndef LCD_Layout_480x320_h
#define LCD_Layout_480x320_h
#include "lcd_driver.h"
#if (defined(LAY_480x320))

#include "fonts.h"

typedef const struct
{
	//Top row of status buttons
	const uint16_t LAY_TOPBUTTONS_X1;
	const uint16_t LAY_TOPBUTTONS_X2;
	const uint16_t LAY_TOPBUTTONS_Y1;
	const uint16_t LAY_TOPBUTTONS_Y2;
	const uint16_t LAY_TOPBUTTONS_WIDTH;
	const uint16_t LAY_TOPBUTTONS_HEIGHT;
	const uint16_t LAY_TOPBUTTONS_TB_MARGIN;
	const uint16_t LAY_TOPBUTTONS_LR_MARGIN;
	const uint16_t LAY_TOPBUTTONS_PRE_X;
	const uint16_t LAY_TOPBUTTONS_PRE_Y;
	const uint16_t LAY_TOPBUTTONS_ATT_X;
	const uint16_t LAY_TOPBUTTONS_ATT_Y;
	const uint16_t LAY_TOPBUTTONS_PGA_X;
	const uint16_t LAY_TOPBUTTONS_PGA_Y;
	const uint16_t LAY_TOPBUTTONS_DRV_X;
	const uint16_t LAY_TOPBUTTONS_DRV_Y;
	const uint16_t LAY_TOPBUTTONS_AGC_X;
	const uint16_t LAY_TOPBUTTONS_AGC_Y;
	const uint16_t LAY_TOPBUTTONS_SECOND_LINE_Y;
	const uint16_t LAY_TOPBUTTONS_DNR_X;
	const uint16_t LAY_TOPBUTTONS_DNR_Y;
	const uint16_t LAY_TOPBUTTONS_NB_X;
	const uint16_t LAY_TOPBUTTONS_NB_Y;
	const uint16_t LAY_TOPBUTTONS_FAST_X;
	const uint16_t LAY_TOPBUTTONS_FAST_Y;
	const uint16_t LAY_TOPBUTTONS_MUTE_X;
	const uint16_t LAY_TOPBUTTONS_MUTE_Y;
	const uint16_t LAY_TOPBUTTONS_LOCK_X;
	const uint16_t LAY_TOPBUTTONS_LOCK_Y;
	//Clock
	const uint16_t LAY_CLOCK_POS_Y;
	const uint16_t LAY_CLOCK_POS_HRS_X;
	const uint16_t LAY_CLOCK_POS_MIN_X;
	const uint16_t LAY_CLOCK_POS_SEC_X;
	const GFXfont *LAY_CLOCK_FONT;
	//WIFI
	const uint16_t LAY_STATUS_WIFI_ICON_X;
	const uint16_t LAY_STATUS_WIFI_ICON_Y;
	//Frequency output
	const uint16_t LAY_FREQ_X_OFFSET_100;
	const uint16_t LAY_FREQ_X_OFFSET_10;
	const uint16_t LAY_FREQ_X_OFFSET_1;
	const uint16_t LAY_FREQ_X_OFFSET_KHZ;
	const uint16_t LAY_FREQ_X_OFFSET_HZ;
	const uint16_t LAY_FREQ_HEIGHT;
	const uint16_t LAY_FREQ_WIDTH;
	const uint16_t LAY_FREQ_TOP_OFFSET;
	const uint16_t LAY_FREQ_LEFT_MARGIN;
	const uint16_t LAY_FREQ_RIGHT_MARGIN;
	const uint16_t LAY_FREQ_BOTTOM_OFFSET;
	const uint16_t LAY_FREQ_BLOCK_HEIGHT;
	const uint16_t LAY_FREQ_Y_TOP;
	const uint16_t LAY_FREQ_Y_BASELINE;
	const uint16_t LAY_FREQ_Y_BASELINE_SMALL;
	const GFXfont *LAY_FREQ_FONT;
	const GFXfont *LAY_FREQ_SMALL_FONT;
	const uint16_t LAY_FREQ_DELIMITER_Y_OFFSET;
	const uint16_t LAY_FREQ_DELIMITER_X1_OFFSET;
	const uint16_t LAY_FREQ_DELIMITER_X2_OFFSET;
	//Display statuses under frequency
	const uint16_t LAY_STATUS_Y_OFFSET;
	const uint16_t LAY_STATUS_HEIGHT;
	const uint16_t LAY_STATUS_BAR_X_OFFSET;
	const uint16_t LAY_STATUS_BAR_Y_OFFSET;
	const uint16_t LAY_STATUS_BAR_HEIGHT;
	const uint16_t LAY_STATUS_TXRX_X_OFFSET;
	const uint16_t LAY_STATUS_TXRX_Y_OFFSET;
	const GFXfont *LAY_STATUS_TXRX_FONT;
	const uint16_t LAY_STATUS_VFO_X_OFFSET;
	const uint16_t LAY_STATUS_VFO_Y_OFFSET;
	const uint16_t LAY_STATUS_VFO_BLOCK_WIDTH;
	const uint16_t LAY_STATUS_VFO_BLOCK_HEIGHT;
	const uint16_t LAY_STATUS_ANT_X_OFFSET;
	const uint16_t LAY_STATUS_ANT_Y_OFFSET;
	const uint16_t LAY_STATUS_ANT_BLOCK_WIDTH;
	const uint16_t LAY_STATUS_ANT_BLOCK_HEIGHT;
	const uint16_t LAY_STATUS_TX_LABELS_OFFSET_X;
	const uint16_t LAY_STATUS_TX_LABELS_MARGIN_X;
	const uint16_t LAY_STATUS_SMETER_WIDTH;
	const uint16_t LAY_STATUS_SMETER_MARKER_HEIGHT;
	const uint16_t LAY_STATUS_PMETER_WIDTH;
	const uint16_t LAY_STATUS_AMETER_WIDTH;
	const uint16_t LAY_STATUS_ALC_BAR_X_OFFSET;
	const uint16_t LAY_STATUS_LABELS_OFFSET_Y;
	const uint8_t LAY_STATUS_LABELS_FONT_SIZE;
	const uint16_t LAY_STATUS_LABEL_S_VAL_X_OFFSET;
	const uint16_t LAY_STATUS_LABEL_S_VAL_Y_OFFSET;
	const GFXfont *LAY_STATUS_LABEL_S_VAL_FONT;
	const uint16_t LAY_STATUS_LABEL_DBM_X_OFFSET;
	const uint16_t LAY_STATUS_LABEL_DBM_Y_OFFSET;
	const uint16_t LAY_STATUS_LABEL_BW_X_OFFSET;
	const uint16_t LAY_STATUS_LABEL_BW_Y_OFFSET;
	const uint16_t LAY_STATUS_LABEL_RIT_X_OFFSET;
	const uint16_t LAY_STATUS_LABEL_RIT_Y_OFFSET;
	const uint16_t LAY_STATUS_LABEL_THERM_X_OFFSET;
	const uint16_t LAY_STATUS_LABEL_THERM_Y_OFFSET;
	const uint16_t LAY_STATUS_LABEL_NOTCH_X_OFFSET;
	const uint16_t LAY_STATUS_LABEL_NOTCH_Y_OFFSET;
	const uint16_t LAY_STATUS_LABEL_FFT_BW_X_OFFSET;
	const uint16_t LAY_STATUS_LABEL_FFT_BW_Y_OFFSET;
	const uint16_t LAY_STATUS_SMETER_PEAK_HOLDTIME;
	const uint16_t LAY_STATUS_SMETER_TXLABELS_MARGIN;
	const uint16_t LAY_STATUS_SMETER_TXLABELS_PADDING;
	const uint16_t LAY_STATUS_TX_LABELS_VAL_WIDTH;
	const uint16_t LAY_STATUS_TX_LABELS_VAL_HEIGHT;
	const uint16_t LAY_STATUS_TX_ALC_X_OFFSET;
	const uint16_t LAY_STATUS_MODE_X_OFFSET;
	const uint16_t LAY_STATUS_MODE_Y_OFFSET;
	const uint16_t LAY_STATUS_MODE_BLOCK_WIDTH;
	const uint16_t LAY_STATUS_MODE_BLOCK_HEIGHT;
	const uint16_t LAY_STATUS_ERR_OFFSET_X;
	const uint16_t LAY_STATUS_ERR_OFFSET_Y;
	const uint16_t LAY_STATUS_ERR_WIDTH;
	const uint16_t LAY_STATUS_ERR_HEIGHT;
	const uint16_t LAY_STATUS_ERR2_OFFSET_X;
	const uint8_t LAY_TEXTBAR_FONT;
	const uint16_t LAY_TEXTBAR_TEXT_X_OFFSET;
	//FFT and waterfall
	const uint16_t LAY_FFT_HEIGHT_STYLE1;
	const uint16_t LAY_WTF_HEIGHT_STYLE1;
	const uint16_t LAY_FFT_HEIGHT_STYLE2;
	const uint16_t LAY_WTF_HEIGHT_STYLE2;
	const uint16_t LAY_FFT_HEIGHT_STYLE3;
	const uint16_t LAY_WTF_HEIGHT_STYLE3;
	const uint16_t LAY_FFT_PRINT_SIZE;
	const uint16_t LAY_FFT_CWDECODER_OFFSET;
	const uint16_t LAY_FFT_FFT_MAX_HEIGHT;
	const uint16_t LAY_FFT_WTF_MAX_HEIGHT;
	const uint16_t LAY_FFT_FFTWTF_POS_Y;
	const uint16_t LAY_FFT_FFTWTF_HEIGHT;
	//System menu
	const uint16_t LAY_SYSMENU_X1;
	const uint16_t LAY_SYSMENU_X2;
	const uint16_t LAY_SYSMENU_X2_BIGINT;
	const uint16_t LAY_SYSMENU_X2R_BIGINT;
	const uint16_t LAY_SYSMENU_W;
	const uint16_t LAY_SYSMENU_ITEM_HEIGHT;
	const uint16_t LAY_SYSMENU_MAX_ITEMS_ON_PAGE;
	//Stuff
	const uint16_t LAY_GREETINGS_X;
	const uint16_t LAY_GREETINGS_Y;
	//Tooltip
	const uint16_t LAY_TOOLTIP_TIMEOUT;
	const uint16_t LAY_TOOLTIP_MARGIN;
	const uint16_t LAY_TOOLTIP_POS_X;
	const uint16_t LAY_TOOLTIP_POS_Y;
} STRUCT_LAYOUT_THEME;


static const STRUCT_LAYOUT_THEME LAYOUT_THEMES[1] = 
{
	{
		//Top row of status buttons
		.LAY_TOPBUTTONS_X1 = 0,
		.LAY_TOPBUTTONS_X2 = (LCD_WIDTH - 1),
		.LAY_TOPBUTTONS_Y1 = 1,
		.LAY_TOPBUTTONS_Y2 = 56,
		.LAY_TOPBUTTONS_WIDTH = 72,
		.LAY_TOPBUTTONS_HEIGHT = 22,
		.LAY_TOPBUTTONS_TB_MARGIN = 2,
		.LAY_TOPBUTTONS_LR_MARGIN = 2,
		.LAY_TOPBUTTONS_PRE_X = 2, //LAY_TOPBUTTONS_X1 + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_PRE_Y = 1, //LAY_TOPBUTTONS_Y1
		.LAY_TOPBUTTONS_ATT_X = 76, //LAY_TOPBUTTONS_PRE_X + LAY_TOPBUTTONS_PRE_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_ATT_Y = 1, //LAY_TOPBUTTONS_Y1
		.LAY_TOPBUTTONS_PGA_X = 150, //LAY_TOPBUTTONS_ATT_X + LAY_TOPBUTTONS_ATT_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_PGA_Y = 1, //LAY_TOPBUTTONS_Y1
		.LAY_TOPBUTTONS_DRV_X = 224, //LAY_TOPBUTTONS_PGA_X + LAY_TOPBUTTONS_PGA_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_DRV_Y = 1, //LAY_TOPBUTTONS_Y1
		.LAY_TOPBUTTONS_AGC_X = 298, //LAY_TOPBUTTONS_DRV_X + LAY_TOPBUTTONS_DRV_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_AGC_Y = 1, //LAY_TOPBUTTONS_Y1
		.LAY_TOPBUTTONS_SECOND_LINE_Y = 25, //LAY_TOPBUTTONS_Y1 + LAY_TOPBUTTONS_HEIGHT + LAY_TOPBUTTONS_TB_MARGIN
		.LAY_TOPBUTTONS_DNR_X = 2, // LAY_TOPBUTTONS_X1 + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_DNR_Y = 25, //LAY_TOPBUTTONS_SECOND_LINE_Y
		.LAY_TOPBUTTONS_NB_X = 76, //LAY_TOPBUTTONS_DNR_X + LAY_TOPBUTTONS_DNR_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_NB_Y = 25, //LAY_TOPBUTTONS_SECOND_LINE_Y
		.LAY_TOPBUTTONS_FAST_X = 150, //LAY_TOPBUTTONS_NB_X + LAY_TOPBUTTONS_NB_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_FAST_Y = 25, //LAY_TOPBUTTONS_SECOND_LINE_Y
		.LAY_TOPBUTTONS_MUTE_X = 224, //LAY_TOPBUTTONS_FAST_X + LAY_TOPBUTTONS_FAST_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_MUTE_Y = 25, //LAY_TOPBUTTONS_SECOND_LINE_Y
		.LAY_TOPBUTTONS_LOCK_X = 298, //LAY_TOPBUTTONS_MUTE_X + LAY_TOPBUTTONS_MUTE_W + LAY_TOPBUTTONS_LR_MARGIN
		.LAY_TOPBUTTONS_LOCK_Y = 25, //LAY_TOPBUTTONS_SECOND_LINE_Y
		//Clock
		.LAY_CLOCK_POS_Y = 17,
		.LAY_CLOCK_POS_HRS_X = (LCD_WIDTH - 75),
		.LAY_CLOCK_POS_MIN_X = ((LCD_WIDTH - 75) + 25),
		.LAY_CLOCK_POS_SEC_X = (((LCD_WIDTH - 75) + 25) + 25),
		.LAY_CLOCK_FONT = &FreeSans9pt7b,
		//WIFI
		.LAY_STATUS_WIFI_ICON_X = (LCD_WIDTH - 98),
		.LAY_STATUS_WIFI_ICON_Y = 3,
		//Frequency output
		.LAY_FREQ_X_OFFSET_100 = 37,
		.LAY_FREQ_X_OFFSET_10 = 73,
		.LAY_FREQ_X_OFFSET_1 = 113,
		.LAY_FREQ_X_OFFSET_KHZ = 170,
		.LAY_FREQ_X_OFFSET_HZ = 307,
		.LAY_FREQ_HEIGHT = 51,
		.LAY_FREQ_WIDTH = 370,
		.LAY_FREQ_TOP_OFFSET = 3,
		.LAY_FREQ_LEFT_MARGIN = 37,
		.LAY_FREQ_RIGHT_MARGIN = (LCD_WIDTH - 37 - 370), //LAY_FREQ_LEFT_MARGIN - LAY_FREQ_WIDTH
		.LAY_FREQ_BOTTOM_OFFSET = 8,
		.LAY_FREQ_BLOCK_HEIGHT = 62, //LAY_FREQ_HEIGHT + LAY_FREQ_TOP_OFFSET + LAY_FREQ_BOTTOM_OFFSET
		.LAY_FREQ_Y_TOP = 56, //LAY_TOPBUTTONS_Y2
		.LAY_FREQ_Y_BASELINE = 110, //LAY_TOPBUTTONS_Y2 + LAY_FREQ_HEIGHT + LAY_FREQ_TOP_OFFSET
		.LAY_FREQ_Y_BASELINE_SMALL = 108, //LAY_FREQ_Y_BASELINE - 2
		.LAY_FREQ_FONT = &FreeSans36pt7b,
		.LAY_FREQ_SMALL_FONT = &Quito32pt7b,
		.LAY_FREQ_DELIMITER_Y_OFFSET = 0,
		.LAY_FREQ_DELIMITER_X1_OFFSET = 151,
		.LAY_FREQ_DELIMITER_X2_OFFSET = 285,
		//Display statuses under frequency
		.LAY_STATUS_Y_OFFSET = (56 + 62 + 1), //LAY_FREQ_Y_TOP + LAY_FREQ_BLOCK_HEIGHT + 1
		.LAY_STATUS_HEIGHT = 44,
		.LAY_STATUS_BAR_X_OFFSET = 60,
		.LAY_STATUS_BAR_Y_OFFSET = 16,
		.LAY_STATUS_BAR_HEIGHT = 10,
		.LAY_STATUS_TXRX_X_OFFSET = 3,
		.LAY_STATUS_TXRX_Y_OFFSET = -50,
		.LAY_STATUS_TXRX_FONT = &FreeSans9pt7b,
		.LAY_STATUS_VFO_X_OFFSET = 0,
		.LAY_STATUS_VFO_Y_OFFSET = -43,
		.LAY_STATUS_VFO_BLOCK_WIDTH = 37,
		.LAY_STATUS_VFO_BLOCK_HEIGHT = 22,
		.LAY_STATUS_ANT_X_OFFSET = 0,
		.LAY_STATUS_ANT_Y_OFFSET = -23,
		.LAY_STATUS_ANT_BLOCK_WIDTH = 37,
		.LAY_STATUS_ANT_BLOCK_HEIGHT = 22,
		.LAY_STATUS_TX_LABELS_OFFSET_X = 5,
		.LAY_STATUS_TX_LABELS_MARGIN_X = 55,
		.LAY_STATUS_SMETER_WIDTH = 400,
		.LAY_STATUS_SMETER_MARKER_HEIGHT = 30,
		.LAY_STATUS_PMETER_WIDTH = 300,
		.LAY_STATUS_AMETER_WIDTH = 90,
		.LAY_STATUS_ALC_BAR_X_OFFSET = 10,
		.LAY_STATUS_LABELS_OFFSET_Y = 0,
		.LAY_STATUS_LABELS_FONT_SIZE = 1,
		.LAY_STATUS_LABEL_S_VAL_X_OFFSET = 12,
		.LAY_STATUS_LABEL_S_VAL_Y_OFFSET = 25,
		.LAY_STATUS_LABEL_S_VAL_FONT = &FreeSans7pt7b,
		.LAY_STATUS_LABEL_DBM_X_OFFSET = 5,
		.LAY_STATUS_LABEL_DBM_Y_OFFSET = 36,
		.LAY_STATUS_LABEL_BW_X_OFFSET = 60,
		.LAY_STATUS_LABEL_BW_Y_OFFSET = 36,
		.LAY_STATUS_LABEL_RIT_X_OFFSET = 160,
		.LAY_STATUS_LABEL_RIT_Y_OFFSET = 36,
		.LAY_STATUS_LABEL_THERM_X_OFFSET = 240,
		.LAY_STATUS_LABEL_THERM_Y_OFFSET = 36,
		.LAY_STATUS_LABEL_NOTCH_X_OFFSET = 335,
		.LAY_STATUS_LABEL_NOTCH_Y_OFFSET = 36,
		.LAY_STATUS_LABEL_FFT_BW_X_OFFSET = 420,
		.LAY_STATUS_LABEL_FFT_BW_Y_OFFSET = 36,
		.LAY_STATUS_SMETER_PEAK_HOLDTIME = 1000,
		.LAY_STATUS_SMETER_TXLABELS_MARGIN = 55,
		.LAY_STATUS_SMETER_TXLABELS_PADDING = 23,
		.LAY_STATUS_TX_LABELS_VAL_WIDTH = 25,
		.LAY_STATUS_TX_LABELS_VAL_HEIGHT = 8,
		.LAY_STATUS_TX_ALC_X_OFFSET = 40,
		.LAY_STATUS_MODE_X_OFFSET = (LCD_WIDTH - (LCD_WIDTH - 37 - 370) + 10), //LCD_WIDTH - LAY_FREQ_RIGHT_MARGIN + 10
		.LAY_STATUS_MODE_Y_OFFSET = -42,
		.LAY_STATUS_MODE_BLOCK_WIDTH = 48,
		.LAY_STATUS_MODE_BLOCK_HEIGHT = 22,
		.LAY_STATUS_ERR_OFFSET_X = 420,
		.LAY_STATUS_ERR_OFFSET_Y = 25,
		.LAY_STATUS_ERR_WIDTH = 50,
		.LAY_STATUS_ERR_HEIGHT = 8,
		.LAY_STATUS_ERR2_OFFSET_X = 27,
		.LAY_TEXTBAR_FONT = 2,
		.LAY_TEXTBAR_TEXT_X_OFFSET = 85,
		//FFT and waterfall CHECK MAX_FFT_HEIGHT AND MAX_WTF_HEIGHT !!!
		.LAY_FFT_HEIGHT_STYLE1 = 50,
		.LAY_WTF_HEIGHT_STYLE1 = 102,
		.LAY_FFT_HEIGHT_STYLE2 = 76,
		.LAY_WTF_HEIGHT_STYLE2 = 76,
		.LAY_FFT_HEIGHT_STYLE3 = 102,
		.LAY_WTF_HEIGHT_STYLE3 = 50,
		.LAY_FFT_PRINT_SIZE = LCD_WIDTH,
		.LAY_FFT_CWDECODER_OFFSET = 17,
		.LAY_FFT_FFTWTF_POS_Y = ((uint16_t)(LCD_HEIGHT - 50 - 102)), //LCD_HEIGHT - LAY_FFT_HEIGHT_STYLE1 - LAY_WTF_HEIGHT_STYLE1
		.LAY_FFT_FFTWTF_HEIGHT = ((uint16_t)(LCD_HEIGHT - 50 - 102) + 50 + 102), //LAY_FFT_FFTWTF_POS_Y + LAY_FFT_HEIGHT_STYLE1 + LAY_WTF_HEIGHT_STYLE1
		//System menu
		.LAY_SYSMENU_X1 = 5,
		.LAY_SYSMENU_X2 = 400,
		.LAY_SYSMENU_X2_BIGINT = 350,
		.LAY_SYSMENU_X2R_BIGINT = 400,
		.LAY_SYSMENU_W = 458,
		.LAY_SYSMENU_ITEM_HEIGHT = 18,
		.LAY_SYSMENU_MAX_ITEMS_ON_PAGE = (LCD_HEIGHT / 18), //LCD_HEIGHT / LAY_SYSMENU_ITEM_HEIGHT
		//Stuff
		.LAY_GREETINGS_X = (LCD_WIDTH / 2 - 5),
		.LAY_GREETINGS_Y = 25,
		//Tooltip
		.LAY_TOOLTIP_TIMEOUT = 1000,
		.LAY_TOOLTIP_MARGIN = 5,
		.LAY_TOOLTIP_POS_X = (LCD_WIDTH / 2),
		.LAY_TOOLTIP_POS_Y = 70,
	},
};

#define LAYOUT_THEMES_COUNT 1
#define MAX_FFT_PRINT_SIZE LCD_WIDTH
#define MAX_FFT_HEIGHT 102
#define MAX_WTF_HEIGHT 102

#endif
#endif
