#ifndef LCD_Layout_480x320_h
#define LCD_Layout_480x320_h
#include "lcd_driver.h"
#if (defined(LAY_480x320))

#include "fonts.h"

typedef const struct
{
	//Top row of status buttons
	const uint16_t TOPBUTTONS_X1;
	const uint16_t TOPBUTTONS_X2;
	const uint16_t TOPBUTTONS_Y1;
	const uint16_t TOPBUTTONS_Y2;
	const uint16_t TOPBUTTONS_WIDTH;
	const uint16_t TOPBUTTONS_HEIGHT;
	const uint16_t TOPBUTTONS_TB_MARGIN;
	const uint16_t TOPBUTTONS_LR_MARGIN;
	const uint16_t TOPBUTTONS_PRE_X;
	const uint16_t TOPBUTTONS_PRE_Y;
	const uint16_t TOPBUTTONS_ATT_X;
	const uint16_t TOPBUTTONS_ATT_Y;
	const uint16_t TOPBUTTONS_PGA_X;
	const uint16_t TOPBUTTONS_PGA_Y;
	const uint16_t TOPBUTTONS_DRV_X;
	const uint16_t TOPBUTTONS_DRV_Y;
	const uint16_t TOPBUTTONS_AGC_X;
	const uint16_t TOPBUTTONS_AGC_Y;
	const uint16_t TOPBUTTONS_SECOND_LINE_Y;
	const uint16_t TOPBUTTONS_DNR_X;
	const uint16_t TOPBUTTONS_DNR_Y;
	const uint16_t TOPBUTTONS_NB_X;
	const uint16_t TOPBUTTONS_NB_Y;
	const uint16_t TOPBUTTONS_FAST_X;
	const uint16_t TOPBUTTONS_FAST_Y;
	const uint16_t TOPBUTTONS_MUTE_X;
	const uint16_t TOPBUTTONS_MUTE_Y;
	const uint16_t TOPBUTTONS_LOCK_X;
	const uint16_t TOPBUTTONS_LOCK_Y;
	//Clock
	const uint16_t CLOCK_POS_Y;
	const uint16_t CLOCK_POS_HRS_X;
	const uint16_t CLOCK_POS_MIN_X;
	const uint16_t CLOCK_POS_SEC_X;
	const GFXfont *CLOCK_FONT;
	//WIFI
	const uint16_t STATUS_WIFI_ICON_X;
	const uint16_t STATUS_WIFI_ICON_Y;
	//Frequency output
	const uint16_t FREQ_X_OFFSET_100;
	const uint16_t FREQ_X_OFFSET_10;
	const uint16_t FREQ_X_OFFSET_1;
	const uint16_t FREQ_X_OFFSET_KHZ;
	const uint16_t FREQ_X_OFFSET_HZ;
	const uint16_t FREQ_HEIGHT;
	const uint16_t FREQ_WIDTH;
	const uint16_t FREQ_TOP_OFFSET;
	const uint16_t FREQ_LEFT_MARGIN;
	const uint16_t FREQ_RIGHT_MARGIN;
	const uint16_t FREQ_BOTTOM_OFFSET;
	const uint16_t FREQ_BLOCK_HEIGHT;
	const uint16_t FREQ_Y_TOP;
	const uint16_t FREQ_Y_BASELINE;
	const uint16_t FREQ_Y_BASELINE_SMALL;
	const GFXfont *FREQ_FONT;
	const GFXfont *FREQ_SMALL_FONT;
	const uint16_t FREQ_DELIMITER_Y_OFFSET;
	const uint16_t FREQ_DELIMITER_X1_OFFSET;
	const uint16_t FREQ_DELIMITER_X2_OFFSET;
	//Display statuses under frequency
	const uint16_t STATUS_Y_OFFSET;
	const uint16_t STATUS_HEIGHT;
	const uint16_t STATUS_BAR_X_OFFSET;
	const uint16_t STATUS_BAR_Y_OFFSET;
	const uint16_t STATUS_BAR_HEIGHT;
	const uint16_t STATUS_TXRX_X_OFFSET;
	const uint16_t STATUS_TXRX_Y_OFFSET;
	const GFXfont *STATUS_TXRX_FONT;
	const uint16_t STATUS_VFO_X_OFFSET;
	const uint16_t STATUS_VFO_Y_OFFSET;
	const uint16_t STATUS_VFO_BLOCK_WIDTH;
	const uint16_t STATUS_VFO_BLOCK_HEIGHT;
	const uint16_t STATUS_ANT_X_OFFSET;
	const uint16_t STATUS_ANT_Y_OFFSET;
	const uint16_t STATUS_ANT_BLOCK_WIDTH;
	const uint16_t STATUS_ANT_BLOCK_HEIGHT;
	const uint16_t STATUS_TX_LABELS_OFFSET_X;
	const uint16_t STATUS_TX_LABELS_MARGIN_X;
	const uint16_t STATUS_SMETER_WIDTH;
	const uint16_t STATUS_SMETER_MARKER_HEIGHT;
	const uint16_t STATUS_PMETER_WIDTH;
	const uint16_t STATUS_AMETER_WIDTH;
	const uint16_t STATUS_ALC_BAR_X_OFFSET;
	const uint16_t STATUS_LABELS_OFFSET_Y;
	const uint8_t STATUS_LABELS_FONT_SIZE;
	const uint16_t STATUS_LABEL_S_VAL_X_OFFSET;
	const uint16_t STATUS_LABEL_S_VAL_Y_OFFSET;
	const GFXfont *STATUS_LABEL_S_VAL_FONT;
	const uint16_t STATUS_LABEL_DBM_X_OFFSET;
	const uint16_t STATUS_LABEL_DBM_Y_OFFSET;
	const uint16_t STATUS_LABEL_BW_X_OFFSET;
	const uint16_t STATUS_LABEL_BW_Y_OFFSET;
	const uint16_t STATUS_LABEL_RIT_X_OFFSET;
	const uint16_t STATUS_LABEL_RIT_Y_OFFSET;
	const uint16_t STATUS_LABEL_THERM_X_OFFSET;
	const uint16_t STATUS_LABEL_THERM_Y_OFFSET;
	const uint16_t STATUS_LABEL_NOTCH_X_OFFSET;
	const uint16_t STATUS_LABEL_NOTCH_Y_OFFSET;
	const uint16_t STATUS_LABEL_FFT_BW_X_OFFSET;
	const uint16_t STATUS_LABEL_FFT_BW_Y_OFFSET;
	const uint16_t STATUS_SMETER_PEAK_HOLDTIME;
	const uint16_t STATUS_SMETER_TXLABELS_MARGIN;
	const uint16_t STATUS_SMETER_TXLABELS_PADDING;
	const uint16_t STATUS_TX_LABELS_VAL_WIDTH;
	const uint16_t STATUS_TX_LABELS_VAL_HEIGHT;
	const uint16_t STATUS_TX_ALC_X_OFFSET;
	const uint16_t STATUS_MODE_X_OFFSET;
	const uint16_t STATUS_MODE_Y_OFFSET;
	const uint16_t STATUS_MODE_BLOCK_WIDTH;
	const uint16_t STATUS_MODE_BLOCK_HEIGHT;
	const uint16_t STATUS_ERR_OFFSET_X;
	const uint16_t STATUS_ERR_OFFSET_Y;
	const uint16_t STATUS_ERR_WIDTH;
	const uint16_t STATUS_ERR_HEIGHT;
	const uint16_t STATUS_ERR2_OFFSET_X;
	const uint8_t TEXTBAR_FONT;
	const uint16_t TEXTBAR_TEXT_X_OFFSET;
	//FFT and waterfall
	const uint16_t FFT_HEIGHT_STYLE1;
	const uint16_t WTF_HEIGHT_STYLE1;
	const uint16_t FFT_HEIGHT_STYLE2;
	const uint16_t WTF_HEIGHT_STYLE2;
	const uint16_t FFT_HEIGHT_STYLE3;
	const uint16_t WTF_HEIGHT_STYLE3;
	const uint16_t FFT_PRINT_SIZE;
	const uint16_t FFT_CWDECODER_OFFSET;
	const uint16_t FFT_FFT_MAX_HEIGHT;
	const uint16_t FFT_WTF_MAX_HEIGHT;
	const uint16_t FFT_FFTWTF_POS_Y;
	const uint16_t FFT_FFTWTF_HEIGHT;
	//System menu
	const uint16_t SYSMENU_X1;
	const uint16_t SYSMENU_X2;
	const uint16_t SYSMENU_X2_BIGINT;
	const uint16_t SYSMENU_X2R_BIGINT;
	const uint16_t SYSMENU_W;
	const uint16_t SYSMENU_ITEM_HEIGHT;
	const uint16_t SYSMENU_MAX_ITEMS_ON_PAGE;
	//Stuff
	const uint16_t GREETINGS_X;
	const uint16_t GREETINGS_Y;
	//Tooltip
	const uint16_t TOOLTIP_TIMEOUT;
	const uint16_t TOOLTIP_MARGIN;
	const uint16_t TOOLTIP_POS_X;
	const uint16_t TOOLTIP_POS_Y;
} STRUCT_LAYOUT_THEME;


static const STRUCT_LAYOUT_THEME LAYOUT_THEMES[1] = 
{
	{
		//Top row of status buttons
		.TOPBUTTONS_X1 = 0,
		.TOPBUTTONS_X2 = (LCD_WIDTH - 1),
		.TOPBUTTONS_Y1 = 1,
		.TOPBUTTONS_Y2 = 56,
		.TOPBUTTONS_WIDTH = 72,
		.TOPBUTTONS_HEIGHT = 22,
		.TOPBUTTONS_TB_MARGIN = 2,
		.TOPBUTTONS_LR_MARGIN = 2,
		.TOPBUTTONS_PRE_X = 2, //TOPBUTTONS_X1 + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_PRE_Y = 1, //TOPBUTTONS_Y1
		.TOPBUTTONS_ATT_X = 76, //TOPBUTTONS_PRE_X + TOPBUTTONS_PRE_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_ATT_Y = 1, //TOPBUTTONS_Y1
		.TOPBUTTONS_PGA_X = 150, //TOPBUTTONS_ATT_X + TOPBUTTONS_ATT_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_PGA_Y = 1, //TOPBUTTONS_Y1
		.TOPBUTTONS_DRV_X = 224, //TOPBUTTONS_PGA_X + TOPBUTTONS_PGA_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_DRV_Y = 1, //TOPBUTTONS_Y1
		.TOPBUTTONS_AGC_X = 298, //TOPBUTTONS_DRV_X + TOPBUTTONS_DRV_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_AGC_Y = 1, //TOPBUTTONS_Y1
		.TOPBUTTONS_SECOND_LINE_Y = 25, //TOPBUTTONS_Y1 + TOPBUTTONS_HEIGHT + TOPBUTTONS_TB_MARGIN
		.TOPBUTTONS_DNR_X = 2, // TOPBUTTONS_X1 + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_DNR_Y = 25, //TOPBUTTONS_SECOND_LINE_Y
		.TOPBUTTONS_NB_X = 76, //TOPBUTTONS_DNR_X + TOPBUTTONS_DNR_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_NB_Y = 25, //TOPBUTTONS_SECOND_LINE_Y
		.TOPBUTTONS_FAST_X = 150, //TOPBUTTONS_NB_X + TOPBUTTONS_NB_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_FAST_Y = 25, //TOPBUTTONS_SECOND_LINE_Y
		.TOPBUTTONS_MUTE_X = 224, //TOPBUTTONS_FAST_X + TOPBUTTONS_FAST_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_MUTE_Y = 25, //TOPBUTTONS_SECOND_LINE_Y
		.TOPBUTTONS_LOCK_X = 298, //TOPBUTTONS_MUTE_X + TOPBUTTONS_MUTE_W + TOPBUTTONS_LR_MARGIN
		.TOPBUTTONS_LOCK_Y = 25, //TOPBUTTONS_SECOND_LINE_Y
		//Clock
		.CLOCK_POS_Y = 17,
		.CLOCK_POS_HRS_X = (LCD_WIDTH - 75),
		.CLOCK_POS_MIN_X = ((LCD_WIDTH - 75) + 25),
		.CLOCK_POS_SEC_X = (((LCD_WIDTH - 75) + 25) + 25),
		.CLOCK_FONT = &FreeSans9pt7b,
		//WIFI
		.STATUS_WIFI_ICON_X = (LCD_WIDTH - 98),
		.STATUS_WIFI_ICON_Y = 3,
		//Frequency output
		.FREQ_X_OFFSET_100 = 37,
		.FREQ_X_OFFSET_10 = 73,
		.FREQ_X_OFFSET_1 = 113,
		.FREQ_X_OFFSET_KHZ = 170,
		.FREQ_X_OFFSET_HZ = 307,
		.FREQ_HEIGHT = 51,
		.FREQ_WIDTH = 370,
		.FREQ_TOP_OFFSET = 3,
		.FREQ_LEFT_MARGIN = 37,
		.FREQ_RIGHT_MARGIN = (LCD_WIDTH - 37 - 370), //FREQ_LEFT_MARGIN - FREQ_WIDTH
		.FREQ_BOTTOM_OFFSET = 8,
		.FREQ_BLOCK_HEIGHT = 62, //FREQ_HEIGHT + FREQ_TOP_OFFSET + FREQ_BOTTOM_OFFSET
		.FREQ_Y_TOP = 56, //TOPBUTTONS_Y2
		.FREQ_Y_BASELINE = 110, //TOPBUTTONS_Y2 + FREQ_HEIGHT + FREQ_TOP_OFFSET
		.FREQ_Y_BASELINE_SMALL = 108, //FREQ_Y_BASELINE - 2
		.FREQ_FONT = &FreeSans36pt7b,
		.FREQ_SMALL_FONT = &Quito32pt7b,
		.FREQ_DELIMITER_Y_OFFSET = 0,
		.FREQ_DELIMITER_X1_OFFSET = 151,
		.FREQ_DELIMITER_X2_OFFSET = 285,
		//Display statuses under frequency
		.STATUS_Y_OFFSET = (56 + 62 + 1), //FREQ_Y_TOP + FREQ_BLOCK_HEIGHT + 1
		.STATUS_HEIGHT = 44,
		.STATUS_BAR_X_OFFSET = 60,
		.STATUS_BAR_Y_OFFSET = 16,
		.STATUS_BAR_HEIGHT = 10,
		.STATUS_TXRX_X_OFFSET = 3,
		.STATUS_TXRX_Y_OFFSET = -50,
		.STATUS_TXRX_FONT = &FreeSans9pt7b,
		.STATUS_VFO_X_OFFSET = 0,
		.STATUS_VFO_Y_OFFSET = -43,
		.STATUS_VFO_BLOCK_WIDTH = 37,
		.STATUS_VFO_BLOCK_HEIGHT = 22,
		.STATUS_ANT_X_OFFSET = 0,
		.STATUS_ANT_Y_OFFSET = -23,
		.STATUS_ANT_BLOCK_WIDTH = 37,
		.STATUS_ANT_BLOCK_HEIGHT = 22,
		.STATUS_TX_LABELS_OFFSET_X = 5,
		.STATUS_TX_LABELS_MARGIN_X = 55,
		.STATUS_SMETER_WIDTH = 400,
		.STATUS_SMETER_MARKER_HEIGHT = 30,
		.STATUS_PMETER_WIDTH = 300,
		.STATUS_AMETER_WIDTH = 90,
		.STATUS_ALC_BAR_X_OFFSET = 10,
		.STATUS_LABELS_OFFSET_Y = 0,
		.STATUS_LABELS_FONT_SIZE = 1,
		.STATUS_LABEL_S_VAL_X_OFFSET = 12,
		.STATUS_LABEL_S_VAL_Y_OFFSET = 25,
		.STATUS_LABEL_S_VAL_FONT = &FreeSans7pt7b,
		.STATUS_LABEL_DBM_X_OFFSET = 5,
		.STATUS_LABEL_DBM_Y_OFFSET = 36,
		.STATUS_LABEL_BW_X_OFFSET = 60,
		.STATUS_LABEL_BW_Y_OFFSET = 36,
		.STATUS_LABEL_RIT_X_OFFSET = 160,
		.STATUS_LABEL_RIT_Y_OFFSET = 36,
		.STATUS_LABEL_THERM_X_OFFSET = 240,
		.STATUS_LABEL_THERM_Y_OFFSET = 36,
		.STATUS_LABEL_NOTCH_X_OFFSET = 335,
		.STATUS_LABEL_NOTCH_Y_OFFSET = 36,
		.STATUS_LABEL_FFT_BW_X_OFFSET = 420,
		.STATUS_LABEL_FFT_BW_Y_OFFSET = 36,
		.STATUS_SMETER_PEAK_HOLDTIME = 1000,
		.STATUS_SMETER_TXLABELS_MARGIN = 55,
		.STATUS_SMETER_TXLABELS_PADDING = 23,
		.STATUS_TX_LABELS_VAL_WIDTH = 25,
		.STATUS_TX_LABELS_VAL_HEIGHT = 8,
		.STATUS_TX_ALC_X_OFFSET = 40,
		.STATUS_MODE_X_OFFSET = (LCD_WIDTH - (LCD_WIDTH - 37 - 370) + 10), //LCD_WIDTH - FREQ_RIGHT_MARGIN + 10
		.STATUS_MODE_Y_OFFSET = -42,
		.STATUS_MODE_BLOCK_WIDTH = 48,
		.STATUS_MODE_BLOCK_HEIGHT = 22,
		.STATUS_ERR_OFFSET_X = 420,
		.STATUS_ERR_OFFSET_Y = 25,
		.STATUS_ERR_WIDTH = 50,
		.STATUS_ERR_HEIGHT = 8,
		.STATUS_ERR2_OFFSET_X = 27,
		.TEXTBAR_FONT = 2,
		.TEXTBAR_TEXT_X_OFFSET = 85,
		//FFT and waterfall CHECK MAX_FFT_HEIGHT AND MAX_WTF_HEIGHT !!!
		.FFT_HEIGHT_STYLE1 = 50,
		.WTF_HEIGHT_STYLE1 = 102,
		.FFT_HEIGHT_STYLE2 = 76,
		.WTF_HEIGHT_STYLE2 = 76,
		.FFT_HEIGHT_STYLE3 = 102,
		.WTF_HEIGHT_STYLE3 = 50,
		.FFT_PRINT_SIZE = LCD_WIDTH,
		.FFT_CWDECODER_OFFSET = 17,
		.FFT_FFTWTF_POS_Y = ((uint16_t)(LCD_HEIGHT - 50 - 102)), //LCD_HEIGHT - FFT_HEIGHT_STYLE1 - WTF_HEIGHT_STYLE1
		.FFT_FFTWTF_HEIGHT = ((uint16_t)(LCD_HEIGHT - 50 - 102) + 50 + 102), //FFT_FFTWTF_POS_Y + FFT_HEIGHT_STYLE1 + WTF_HEIGHT_STYLE1
		//System menu
		.SYSMENU_X1 = 5,
		.SYSMENU_X2 = 400,
		.SYSMENU_X2_BIGINT = 350,
		.SYSMENU_X2R_BIGINT = 400,
		.SYSMENU_W = 458,
		.SYSMENU_ITEM_HEIGHT = 18,
		.SYSMENU_MAX_ITEMS_ON_PAGE = (LCD_HEIGHT / 18), //LCD_HEIGHT / SYSMENU_ITEM_HEIGHT
		//Stuff
		.GREETINGS_X = (LCD_WIDTH / 2 - 5),
		.GREETINGS_Y = 25,
		//Tooltip
		.TOOLTIP_TIMEOUT = 1000,
		.TOOLTIP_MARGIN = 5,
		.TOOLTIP_POS_X = (LCD_WIDTH / 2),
		.TOOLTIP_POS_Y = 70,
	},
};

#define LAYOUT_THEMES_COUNT 1
#define MAX_FFT_PRINT_SIZE LCD_WIDTH
#define MAX_FFT_HEIGHT 102
#define MAX_WTF_HEIGHT 102

#endif
#endif
