-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\nco14\nco14_LookUpTableGen.vhd
-- Created: 2021-02-11 22:59:10
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: nco14_LookUpTableGen
-- Source Path: nco14/NCO HDL Optimized/WaveformGen/LookUpTableGen
-- Hierarchy Level: 3
-- 
-- Look Up Table Generation Component
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.nco14_nco14_pkg.ALL;

ENTITY nco14_LookUpTableGen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        lutaddr                           :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        lutoutput                         :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En13
        );
END nco14_LookUpTableGen;


ARCHITECTURE rtl OF nco14_LookUpTableGen IS

  -- Constants
  CONSTANT Lookup_Table1_table_data       : vector_of_signed14(0 TO 1023) := 
    (to_signed(16#0000#, 14), to_signed(16#000D#, 14), to_signed(16#0019#, 14), to_signed(16#0026#, 14),
     to_signed(16#0032#, 14), to_signed(16#003F#, 14), to_signed(16#004B#, 14), to_signed(16#0058#, 14),
     to_signed(16#0065#, 14), to_signed(16#0071#, 14), to_signed(16#007E#, 14), to_signed(16#008A#, 14),
     to_signed(16#0097#, 14), to_signed(16#00A3#, 14), to_signed(16#00B0#, 14), to_signed(16#00BC#, 14),
     to_signed(16#00C9#, 14), to_signed(16#00D6#, 14), to_signed(16#00E2#, 14), to_signed(16#00EF#, 14),
     to_signed(16#00FB#, 14), to_signed(16#0108#, 14), to_signed(16#0114#, 14), to_signed(16#0121#, 14),
     to_signed(16#012E#, 14), to_signed(16#013A#, 14), to_signed(16#0147#, 14), to_signed(16#0153#, 14),
     to_signed(16#0160#, 14), to_signed(16#016C#, 14), to_signed(16#0179#, 14), to_signed(16#0185#, 14),
     to_signed(16#0192#, 14), to_signed(16#019F#, 14), to_signed(16#01AB#, 14), to_signed(16#01B8#, 14),
     to_signed(16#01C4#, 14), to_signed(16#01D1#, 14), to_signed(16#01DD#, 14), to_signed(16#01EA#, 14),
     to_signed(16#01F6#, 14), to_signed(16#0203#, 14), to_signed(16#020F#, 14), to_signed(16#021C#, 14),
     to_signed(16#0229#, 14), to_signed(16#0235#, 14), to_signed(16#0242#, 14), to_signed(16#024E#, 14),
     to_signed(16#025B#, 14), to_signed(16#0267#, 14), to_signed(16#0274#, 14), to_signed(16#0280#, 14),
     to_signed(16#028D#, 14), to_signed(16#0299#, 14), to_signed(16#02A6#, 14), to_signed(16#02B2#, 14),
     to_signed(16#02BF#, 14), to_signed(16#02CB#, 14), to_signed(16#02D8#, 14), to_signed(16#02E4#, 14),
     to_signed(16#02F1#, 14), to_signed(16#02FD#, 14), to_signed(16#030A#, 14), to_signed(16#0316#, 14),
     to_signed(16#0323#, 14), to_signed(16#032F#, 14), to_signed(16#033C#, 14), to_signed(16#0348#, 14),
     to_signed(16#0355#, 14), to_signed(16#0361#, 14), to_signed(16#036E#, 14), to_signed(16#037A#, 14),
     to_signed(16#0387#, 14), to_signed(16#0393#, 14), to_signed(16#03A0#, 14), to_signed(16#03AC#, 14),
     to_signed(16#03B9#, 14), to_signed(16#03C5#, 14), to_signed(16#03D2#, 14), to_signed(16#03DE#, 14),
     to_signed(16#03EB#, 14), to_signed(16#03F7#, 14), to_signed(16#0404#, 14), to_signed(16#0410#, 14),
     to_signed(16#041D#, 14), to_signed(16#0429#, 14), to_signed(16#0436#, 14), to_signed(16#0442#, 14),
     to_signed(16#044E#, 14), to_signed(16#045B#, 14), to_signed(16#0467#, 14), to_signed(16#0474#, 14),
     to_signed(16#0480#, 14), to_signed(16#048D#, 14), to_signed(16#0499#, 14), to_signed(16#04A6#, 14),
     to_signed(16#04B2#, 14), to_signed(16#04BE#, 14), to_signed(16#04CB#, 14), to_signed(16#04D7#, 14),
     to_signed(16#04E4#, 14), to_signed(16#04F0#, 14), to_signed(16#04FD#, 14), to_signed(16#0509#, 14),
     to_signed(16#0515#, 14), to_signed(16#0522#, 14), to_signed(16#052E#, 14), to_signed(16#053B#, 14),
     to_signed(16#0547#, 14), to_signed(16#0553#, 14), to_signed(16#0560#, 14), to_signed(16#056C#, 14),
     to_signed(16#0579#, 14), to_signed(16#0585#, 14), to_signed(16#0591#, 14), to_signed(16#059E#, 14),
     to_signed(16#05AA#, 14), to_signed(16#05B6#, 14), to_signed(16#05C3#, 14), to_signed(16#05CF#, 14),
     to_signed(16#05DB#, 14), to_signed(16#05E8#, 14), to_signed(16#05F4#, 14), to_signed(16#0601#, 14),
     to_signed(16#060D#, 14), to_signed(16#0619#, 14), to_signed(16#0626#, 14), to_signed(16#0632#, 14),
     to_signed(16#063E#, 14), to_signed(16#064B#, 14), to_signed(16#0657#, 14), to_signed(16#0663#, 14),
     to_signed(16#066F#, 14), to_signed(16#067C#, 14), to_signed(16#0688#, 14), to_signed(16#0694#, 14),
     to_signed(16#06A1#, 14), to_signed(16#06AD#, 14), to_signed(16#06B9#, 14), to_signed(16#06C6#, 14),
     to_signed(16#06D2#, 14), to_signed(16#06DE#, 14), to_signed(16#06EA#, 14), to_signed(16#06F7#, 14),
     to_signed(16#0703#, 14), to_signed(16#070F#, 14), to_signed(16#071B#, 14), to_signed(16#0728#, 14),
     to_signed(16#0734#, 14), to_signed(16#0740#, 14), to_signed(16#074C#, 14), to_signed(16#0759#, 14),
     to_signed(16#0765#, 14), to_signed(16#0771#, 14), to_signed(16#077D#, 14), to_signed(16#0789#, 14),
     to_signed(16#0796#, 14), to_signed(16#07A2#, 14), to_signed(16#07AE#, 14), to_signed(16#07BA#, 14),
     to_signed(16#07C6#, 14), to_signed(16#07D3#, 14), to_signed(16#07DF#, 14), to_signed(16#07EB#, 14),
     to_signed(16#07F7#, 14), to_signed(16#0803#, 14), to_signed(16#0810#, 14), to_signed(16#081C#, 14),
     to_signed(16#0828#, 14), to_signed(16#0834#, 14), to_signed(16#0840#, 14), to_signed(16#084C#, 14),
     to_signed(16#0858#, 14), to_signed(16#0865#, 14), to_signed(16#0871#, 14), to_signed(16#087D#, 14),
     to_signed(16#0889#, 14), to_signed(16#0895#, 14), to_signed(16#08A1#, 14), to_signed(16#08AD#, 14),
     to_signed(16#08B9#, 14), to_signed(16#08C5#, 14), to_signed(16#08D1#, 14), to_signed(16#08DE#, 14),
     to_signed(16#08EA#, 14), to_signed(16#08F6#, 14), to_signed(16#0902#, 14), to_signed(16#090E#, 14),
     to_signed(16#091A#, 14), to_signed(16#0926#, 14), to_signed(16#0932#, 14), to_signed(16#093E#, 14),
     to_signed(16#094A#, 14), to_signed(16#0956#, 14), to_signed(16#0962#, 14), to_signed(16#096E#, 14),
     to_signed(16#097A#, 14), to_signed(16#0986#, 14), to_signed(16#0992#, 14), to_signed(16#099E#, 14),
     to_signed(16#09AA#, 14), to_signed(16#09B6#, 14), to_signed(16#09C2#, 14), to_signed(16#09CE#, 14),
     to_signed(16#09DA#, 14), to_signed(16#09E6#, 14), to_signed(16#09F2#, 14), to_signed(16#09FE#, 14),
     to_signed(16#0A0A#, 14), to_signed(16#0A16#, 14), to_signed(16#0A22#, 14), to_signed(16#0A2D#, 14),
     to_signed(16#0A39#, 14), to_signed(16#0A45#, 14), to_signed(16#0A51#, 14), to_signed(16#0A5D#, 14),
     to_signed(16#0A69#, 14), to_signed(16#0A75#, 14), to_signed(16#0A81#, 14), to_signed(16#0A8D#, 14),
     to_signed(16#0A98#, 14), to_signed(16#0AA4#, 14), to_signed(16#0AB0#, 14), to_signed(16#0ABC#, 14),
     to_signed(16#0AC8#, 14), to_signed(16#0AD4#, 14), to_signed(16#0ADF#, 14), to_signed(16#0AEB#, 14),
     to_signed(16#0AF7#, 14), to_signed(16#0B03#, 14), to_signed(16#0B0F#, 14), to_signed(16#0B1A#, 14),
     to_signed(16#0B26#, 14), to_signed(16#0B32#, 14), to_signed(16#0B3E#, 14), to_signed(16#0B4A#, 14),
     to_signed(16#0B55#, 14), to_signed(16#0B61#, 14), to_signed(16#0B6D#, 14), to_signed(16#0B79#, 14),
     to_signed(16#0B84#, 14), to_signed(16#0B90#, 14), to_signed(16#0B9C#, 14), to_signed(16#0BA7#, 14),
     to_signed(16#0BB3#, 14), to_signed(16#0BBF#, 14), to_signed(16#0BCA#, 14), to_signed(16#0BD6#, 14),
     to_signed(16#0BE2#, 14), to_signed(16#0BED#, 14), to_signed(16#0BF9#, 14), to_signed(16#0C05#, 14),
     to_signed(16#0C10#, 14), to_signed(16#0C1C#, 14), to_signed(16#0C28#, 14), to_signed(16#0C33#, 14),
     to_signed(16#0C3F#, 14), to_signed(16#0C4B#, 14), to_signed(16#0C56#, 14), to_signed(16#0C62#, 14),
     to_signed(16#0C6D#, 14), to_signed(16#0C79#, 14), to_signed(16#0C84#, 14), to_signed(16#0C90#, 14),
     to_signed(16#0C9C#, 14), to_signed(16#0CA7#, 14), to_signed(16#0CB3#, 14), to_signed(16#0CBE#, 14),
     to_signed(16#0CCA#, 14), to_signed(16#0CD5#, 14), to_signed(16#0CE1#, 14), to_signed(16#0CEC#, 14),
     to_signed(16#0CF8#, 14), to_signed(16#0D03#, 14), to_signed(16#0D0F#, 14), to_signed(16#0D1A#, 14),
     to_signed(16#0D26#, 14), to_signed(16#0D31#, 14), to_signed(16#0D3D#, 14), to_signed(16#0D48#, 14),
     to_signed(16#0D53#, 14), to_signed(16#0D5F#, 14), to_signed(16#0D6A#, 14), to_signed(16#0D76#, 14),
     to_signed(16#0D81#, 14), to_signed(16#0D8C#, 14), to_signed(16#0D98#, 14), to_signed(16#0DA3#, 14),
     to_signed(16#0DAF#, 14), to_signed(16#0DBA#, 14), to_signed(16#0DC5#, 14), to_signed(16#0DD1#, 14),
     to_signed(16#0DDC#, 14), to_signed(16#0DE7#, 14), to_signed(16#0DF3#, 14), to_signed(16#0DFE#, 14),
     to_signed(16#0E09#, 14), to_signed(16#0E14#, 14), to_signed(16#0E20#, 14), to_signed(16#0E2B#, 14),
     to_signed(16#0E36#, 14), to_signed(16#0E42#, 14), to_signed(16#0E4D#, 14), to_signed(16#0E58#, 14),
     to_signed(16#0E63#, 14), to_signed(16#0E6E#, 14), to_signed(16#0E7A#, 14), to_signed(16#0E85#, 14),
     to_signed(16#0E90#, 14), to_signed(16#0E9B#, 14), to_signed(16#0EA6#, 14), to_signed(16#0EB2#, 14),
     to_signed(16#0EBD#, 14), to_signed(16#0EC8#, 14), to_signed(16#0ED3#, 14), to_signed(16#0EDE#, 14),
     to_signed(16#0EE9#, 14), to_signed(16#0EF4#, 14), to_signed(16#0EFF#, 14), to_signed(16#0F0B#, 14),
     to_signed(16#0F16#, 14), to_signed(16#0F21#, 14), to_signed(16#0F2C#, 14), to_signed(16#0F37#, 14),
     to_signed(16#0F42#, 14), to_signed(16#0F4D#, 14), to_signed(16#0F58#, 14), to_signed(16#0F63#, 14),
     to_signed(16#0F6E#, 14), to_signed(16#0F79#, 14), to_signed(16#0F84#, 14), to_signed(16#0F8F#, 14),
     to_signed(16#0F9A#, 14), to_signed(16#0FA5#, 14), to_signed(16#0FB0#, 14), to_signed(16#0FBB#, 14),
     to_signed(16#0FC6#, 14), to_signed(16#0FD1#, 14), to_signed(16#0FDC#, 14), to_signed(16#0FE7#, 14),
     to_signed(16#0FF1#, 14), to_signed(16#0FFC#, 14), to_signed(16#1007#, 14), to_signed(16#1012#, 14),
     to_signed(16#101D#, 14), to_signed(16#1028#, 14), to_signed(16#1033#, 14), to_signed(16#103E#, 14),
     to_signed(16#1048#, 14), to_signed(16#1053#, 14), to_signed(16#105E#, 14), to_signed(16#1069#, 14),
     to_signed(16#1074#, 14), to_signed(16#107E#, 14), to_signed(16#1089#, 14), to_signed(16#1094#, 14),
     to_signed(16#109F#, 14), to_signed(16#10A9#, 14), to_signed(16#10B4#, 14), to_signed(16#10BF#, 14),
     to_signed(16#10C9#, 14), to_signed(16#10D4#, 14), to_signed(16#10DF#, 14), to_signed(16#10E9#, 14),
     to_signed(16#10F4#, 14), to_signed(16#10FF#, 14), to_signed(16#1109#, 14), to_signed(16#1114#, 14),
     to_signed(16#111F#, 14), to_signed(16#1129#, 14), to_signed(16#1134#, 14), to_signed(16#113F#, 14),
     to_signed(16#1149#, 14), to_signed(16#1154#, 14), to_signed(16#115E#, 14), to_signed(16#1169#, 14),
     to_signed(16#1173#, 14), to_signed(16#117E#, 14), to_signed(16#1188#, 14), to_signed(16#1193#, 14),
     to_signed(16#119D#, 14), to_signed(16#11A8#, 14), to_signed(16#11B2#, 14), to_signed(16#11BD#, 14),
     to_signed(16#11C7#, 14), to_signed(16#11D2#, 14), to_signed(16#11DC#, 14), to_signed(16#11E7#, 14),
     to_signed(16#11F1#, 14), to_signed(16#11FB#, 14), to_signed(16#1206#, 14), to_signed(16#1210#, 14),
     to_signed(16#121A#, 14), to_signed(16#1225#, 14), to_signed(16#122F#, 14), to_signed(16#123A#, 14),
     to_signed(16#1244#, 14), to_signed(16#124E#, 14), to_signed(16#1258#, 14), to_signed(16#1263#, 14),
     to_signed(16#126D#, 14), to_signed(16#1277#, 14), to_signed(16#1282#, 14), to_signed(16#128C#, 14),
     to_signed(16#1296#, 14), to_signed(16#12A0#, 14), to_signed(16#12AA#, 14), to_signed(16#12B5#, 14),
     to_signed(16#12BF#, 14), to_signed(16#12C9#, 14), to_signed(16#12D3#, 14), to_signed(16#12DD#, 14),
     to_signed(16#12E8#, 14), to_signed(16#12F2#, 14), to_signed(16#12FC#, 14), to_signed(16#1306#, 14),
     to_signed(16#1310#, 14), to_signed(16#131A#, 14), to_signed(16#1324#, 14), to_signed(16#132E#, 14),
     to_signed(16#1338#, 14), to_signed(16#1342#, 14), to_signed(16#134C#, 14), to_signed(16#1356#, 14),
     to_signed(16#1360#, 14), to_signed(16#136A#, 14), to_signed(16#1374#, 14), to_signed(16#137E#, 14),
     to_signed(16#1388#, 14), to_signed(16#1392#, 14), to_signed(16#139C#, 14), to_signed(16#13A6#, 14),
     to_signed(16#13B0#, 14), to_signed(16#13BA#, 14), to_signed(16#13C4#, 14), to_signed(16#13CE#, 14),
     to_signed(16#13D8#, 14), to_signed(16#13E1#, 14), to_signed(16#13EB#, 14), to_signed(16#13F5#, 14),
     to_signed(16#13FF#, 14), to_signed(16#1409#, 14), to_signed(16#1412#, 14), to_signed(16#141C#, 14),
     to_signed(16#1426#, 14), to_signed(16#1430#, 14), to_signed(16#1439#, 14), to_signed(16#1443#, 14),
     to_signed(16#144D#, 14), to_signed(16#1457#, 14), to_signed(16#1460#, 14), to_signed(16#146A#, 14),
     to_signed(16#1474#, 14), to_signed(16#147D#, 14), to_signed(16#1487#, 14), to_signed(16#1491#, 14),
     to_signed(16#149A#, 14), to_signed(16#14A4#, 14), to_signed(16#14AD#, 14), to_signed(16#14B7#, 14),
     to_signed(16#14C1#, 14), to_signed(16#14CA#, 14), to_signed(16#14D4#, 14), to_signed(16#14DD#, 14),
     to_signed(16#14E7#, 14), to_signed(16#14F0#, 14), to_signed(16#14FA#, 14), to_signed(16#1503#, 14),
     to_signed(16#150D#, 14), to_signed(16#1516#, 14), to_signed(16#1520#, 14), to_signed(16#1529#, 14),
     to_signed(16#1533#, 14), to_signed(16#153C#, 14), to_signed(16#1545#, 14), to_signed(16#154F#, 14),
     to_signed(16#1558#, 14), to_signed(16#1561#, 14), to_signed(16#156B#, 14), to_signed(16#1574#, 14),
     to_signed(16#157D#, 14), to_signed(16#1587#, 14), to_signed(16#1590#, 14), to_signed(16#1599#, 14),
     to_signed(16#15A3#, 14), to_signed(16#15AC#, 14), to_signed(16#15B5#, 14), to_signed(16#15BE#, 14),
     to_signed(16#15C7#, 14), to_signed(16#15D1#, 14), to_signed(16#15DA#, 14), to_signed(16#15E3#, 14),
     to_signed(16#15EC#, 14), to_signed(16#15F5#, 14), to_signed(16#15FE#, 14), to_signed(16#1608#, 14),
     to_signed(16#1611#, 14), to_signed(16#161A#, 14), to_signed(16#1623#, 14), to_signed(16#162C#, 14),
     to_signed(16#1635#, 14), to_signed(16#163E#, 14), to_signed(16#1647#, 14), to_signed(16#1650#, 14),
     to_signed(16#1659#, 14), to_signed(16#1662#, 14), to_signed(16#166B#, 14), to_signed(16#1674#, 14),
     to_signed(16#167D#, 14), to_signed(16#1686#, 14), to_signed(16#168F#, 14), to_signed(16#1698#, 14),
     to_signed(16#16A1#, 14), to_signed(16#16A9#, 14), to_signed(16#16B2#, 14), to_signed(16#16BB#, 14),
     to_signed(16#16C4#, 14), to_signed(16#16CD#, 14), to_signed(16#16D6#, 14), to_signed(16#16DE#, 14),
     to_signed(16#16E7#, 14), to_signed(16#16F0#, 14), to_signed(16#16F9#, 14), to_signed(16#1702#, 14),
     to_signed(16#170A#, 14), to_signed(16#1713#, 14), to_signed(16#171C#, 14), to_signed(16#1724#, 14),
     to_signed(16#172D#, 14), to_signed(16#1736#, 14), to_signed(16#173E#, 14), to_signed(16#1747#, 14),
     to_signed(16#1750#, 14), to_signed(16#1758#, 14), to_signed(16#1761#, 14), to_signed(16#1769#, 14),
     to_signed(16#1772#, 14), to_signed(16#177A#, 14), to_signed(16#1783#, 14), to_signed(16#178B#, 14),
     to_signed(16#1794#, 14), to_signed(16#179C#, 14), to_signed(16#17A5#, 14), to_signed(16#17AD#, 14),
     to_signed(16#17B6#, 14), to_signed(16#17BE#, 14), to_signed(16#17C7#, 14), to_signed(16#17CF#, 14),
     to_signed(16#17D8#, 14), to_signed(16#17E0#, 14), to_signed(16#17E8#, 14), to_signed(16#17F1#, 14),
     to_signed(16#17F9#, 14), to_signed(16#1801#, 14), to_signed(16#180A#, 14), to_signed(16#1812#, 14),
     to_signed(16#181A#, 14), to_signed(16#1822#, 14), to_signed(16#182B#, 14), to_signed(16#1833#, 14),
     to_signed(16#183B#, 14), to_signed(16#1843#, 14), to_signed(16#184B#, 14), to_signed(16#1854#, 14),
     to_signed(16#185C#, 14), to_signed(16#1864#, 14), to_signed(16#186C#, 14), to_signed(16#1874#, 14),
     to_signed(16#187C#, 14), to_signed(16#1884#, 14), to_signed(16#188C#, 14), to_signed(16#1894#, 14),
     to_signed(16#189C#, 14), to_signed(16#18A5#, 14), to_signed(16#18AD#, 14), to_signed(16#18B5#, 14),
     to_signed(16#18BD#, 14), to_signed(16#18C4#, 14), to_signed(16#18CC#, 14), to_signed(16#18D4#, 14),
     to_signed(16#18DC#, 14), to_signed(16#18E4#, 14), to_signed(16#18EC#, 14), to_signed(16#18F4#, 14),
     to_signed(16#18FC#, 14), to_signed(16#1904#, 14), to_signed(16#190B#, 14), to_signed(16#1913#, 14),
     to_signed(16#191B#, 14), to_signed(16#1923#, 14), to_signed(16#192B#, 14), to_signed(16#1932#, 14),
     to_signed(16#193A#, 14), to_signed(16#1942#, 14), to_signed(16#194A#, 14), to_signed(16#1951#, 14),
     to_signed(16#1959#, 14), to_signed(16#1961#, 14), to_signed(16#1968#, 14), to_signed(16#1970#, 14),
     to_signed(16#1977#, 14), to_signed(16#197F#, 14), to_signed(16#1987#, 14), to_signed(16#198E#, 14),
     to_signed(16#1996#, 14), to_signed(16#199D#, 14), to_signed(16#19A5#, 14), to_signed(16#19AC#, 14),
     to_signed(16#19B4#, 14), to_signed(16#19BB#, 14), to_signed(16#19C3#, 14), to_signed(16#19CA#, 14),
     to_signed(16#19D2#, 14), to_signed(16#19D9#, 14), to_signed(16#19E1#, 14), to_signed(16#19E8#, 14),
     to_signed(16#19EF#, 14), to_signed(16#19F7#, 14), to_signed(16#19FE#, 14), to_signed(16#1A05#, 14),
     to_signed(16#1A0D#, 14), to_signed(16#1A14#, 14), to_signed(16#1A1B#, 14), to_signed(16#1A22#, 14),
     to_signed(16#1A2A#, 14), to_signed(16#1A31#, 14), to_signed(16#1A38#, 14), to_signed(16#1A3F#, 14),
     to_signed(16#1A46#, 14), to_signed(16#1A4E#, 14), to_signed(16#1A55#, 14), to_signed(16#1A5C#, 14),
     to_signed(16#1A63#, 14), to_signed(16#1A6A#, 14), to_signed(16#1A71#, 14), to_signed(16#1A78#, 14),
     to_signed(16#1A7F#, 14), to_signed(16#1A86#, 14), to_signed(16#1A8D#, 14), to_signed(16#1A94#, 14),
     to_signed(16#1A9B#, 14), to_signed(16#1AA2#, 14), to_signed(16#1AA9#, 14), to_signed(16#1AB0#, 14),
     to_signed(16#1AB7#, 14), to_signed(16#1ABE#, 14), to_signed(16#1AC5#, 14), to_signed(16#1ACC#, 14),
     to_signed(16#1AD3#, 14), to_signed(16#1ADA#, 14), to_signed(16#1AE0#, 14), to_signed(16#1AE7#, 14),
     to_signed(16#1AEE#, 14), to_signed(16#1AF5#, 14), to_signed(16#1AFC#, 14), to_signed(16#1B02#, 14),
     to_signed(16#1B09#, 14), to_signed(16#1B10#, 14), to_signed(16#1B16#, 14), to_signed(16#1B1D#, 14),
     to_signed(16#1B24#, 14), to_signed(16#1B2A#, 14), to_signed(16#1B31#, 14), to_signed(16#1B38#, 14),
     to_signed(16#1B3E#, 14), to_signed(16#1B45#, 14), to_signed(16#1B4B#, 14), to_signed(16#1B52#, 14),
     to_signed(16#1B59#, 14), to_signed(16#1B5F#, 14), to_signed(16#1B66#, 14), to_signed(16#1B6C#, 14),
     to_signed(16#1B73#, 14), to_signed(16#1B79#, 14), to_signed(16#1B7F#, 14), to_signed(16#1B86#, 14),
     to_signed(16#1B8C#, 14), to_signed(16#1B93#, 14), to_signed(16#1B99#, 14), to_signed(16#1B9F#, 14),
     to_signed(16#1BA6#, 14), to_signed(16#1BAC#, 14), to_signed(16#1BB2#, 14), to_signed(16#1BB9#, 14),
     to_signed(16#1BBF#, 14), to_signed(16#1BC5#, 14), to_signed(16#1BCB#, 14), to_signed(16#1BD2#, 14),
     to_signed(16#1BD8#, 14), to_signed(16#1BDE#, 14), to_signed(16#1BE4#, 14), to_signed(16#1BEA#, 14),
     to_signed(16#1BF0#, 14), to_signed(16#1BF7#, 14), to_signed(16#1BFD#, 14), to_signed(16#1C03#, 14),
     to_signed(16#1C09#, 14), to_signed(16#1C0F#, 14), to_signed(16#1C15#, 14), to_signed(16#1C1B#, 14),
     to_signed(16#1C21#, 14), to_signed(16#1C27#, 14), to_signed(16#1C2D#, 14), to_signed(16#1C33#, 14),
     to_signed(16#1C39#, 14), to_signed(16#1C3F#, 14), to_signed(16#1C45#, 14), to_signed(16#1C4A#, 14),
     to_signed(16#1C50#, 14), to_signed(16#1C56#, 14), to_signed(16#1C5C#, 14), to_signed(16#1C62#, 14),
     to_signed(16#1C68#, 14), to_signed(16#1C6D#, 14), to_signed(16#1C73#, 14), to_signed(16#1C79#, 14),
     to_signed(16#1C7F#, 14), to_signed(16#1C84#, 14), to_signed(16#1C8A#, 14), to_signed(16#1C90#, 14),
     to_signed(16#1C95#, 14), to_signed(16#1C9B#, 14), to_signed(16#1CA1#, 14), to_signed(16#1CA6#, 14),
     to_signed(16#1CAC#, 14), to_signed(16#1CB1#, 14), to_signed(16#1CB7#, 14), to_signed(16#1CBC#, 14),
     to_signed(16#1CC2#, 14), to_signed(16#1CC7#, 14), to_signed(16#1CCD#, 14), to_signed(16#1CD2#, 14),
     to_signed(16#1CD8#, 14), to_signed(16#1CDD#, 14), to_signed(16#1CE3#, 14), to_signed(16#1CE8#, 14),
     to_signed(16#1CED#, 14), to_signed(16#1CF3#, 14), to_signed(16#1CF8#, 14), to_signed(16#1CFE#, 14),
     to_signed(16#1D03#, 14), to_signed(16#1D08#, 14), to_signed(16#1D0D#, 14), to_signed(16#1D13#, 14),
     to_signed(16#1D18#, 14), to_signed(16#1D1D#, 14), to_signed(16#1D22#, 14), to_signed(16#1D28#, 14),
     to_signed(16#1D2D#, 14), to_signed(16#1D32#, 14), to_signed(16#1D37#, 14), to_signed(16#1D3C#, 14),
     to_signed(16#1D41#, 14), to_signed(16#1D46#, 14), to_signed(16#1D4B#, 14), to_signed(16#1D50#, 14),
     to_signed(16#1D55#, 14), to_signed(16#1D5A#, 14), to_signed(16#1D5F#, 14), to_signed(16#1D64#, 14),
     to_signed(16#1D69#, 14), to_signed(16#1D6E#, 14), to_signed(16#1D73#, 14), to_signed(16#1D78#, 14),
     to_signed(16#1D7D#, 14), to_signed(16#1D82#, 14), to_signed(16#1D87#, 14), to_signed(16#1D8C#, 14),
     to_signed(16#1D90#, 14), to_signed(16#1D95#, 14), to_signed(16#1D9A#, 14), to_signed(16#1D9F#, 14),
     to_signed(16#1DA4#, 14), to_signed(16#1DA8#, 14), to_signed(16#1DAD#, 14), to_signed(16#1DB2#, 14),
     to_signed(16#1DB6#, 14), to_signed(16#1DBB#, 14), to_signed(16#1DC0#, 14), to_signed(16#1DC4#, 14),
     to_signed(16#1DC9#, 14), to_signed(16#1DCD#, 14), to_signed(16#1DD2#, 14), to_signed(16#1DD7#, 14),
     to_signed(16#1DDB#, 14), to_signed(16#1DE0#, 14), to_signed(16#1DE4#, 14), to_signed(16#1DE9#, 14),
     to_signed(16#1DED#, 14), to_signed(16#1DF1#, 14), to_signed(16#1DF6#, 14), to_signed(16#1DFA#, 14),
     to_signed(16#1DFF#, 14), to_signed(16#1E03#, 14), to_signed(16#1E07#, 14), to_signed(16#1E0C#, 14),
     to_signed(16#1E10#, 14), to_signed(16#1E14#, 14), to_signed(16#1E19#, 14), to_signed(16#1E1D#, 14),
     to_signed(16#1E21#, 14), to_signed(16#1E25#, 14), to_signed(16#1E2A#, 14), to_signed(16#1E2E#, 14),
     to_signed(16#1E32#, 14), to_signed(16#1E36#, 14), to_signed(16#1E3A#, 14), to_signed(16#1E3E#, 14),
     to_signed(16#1E42#, 14), to_signed(16#1E46#, 14), to_signed(16#1E4B#, 14), to_signed(16#1E4F#, 14),
     to_signed(16#1E53#, 14), to_signed(16#1E57#, 14), to_signed(16#1E5B#, 14), to_signed(16#1E5F#, 14),
     to_signed(16#1E63#, 14), to_signed(16#1E66#, 14), to_signed(16#1E6A#, 14), to_signed(16#1E6E#, 14),
     to_signed(16#1E72#, 14), to_signed(16#1E76#, 14), to_signed(16#1E7A#, 14), to_signed(16#1E7E#, 14),
     to_signed(16#1E81#, 14), to_signed(16#1E85#, 14), to_signed(16#1E89#, 14), to_signed(16#1E8D#, 14),
     to_signed(16#1E91#, 14), to_signed(16#1E94#, 14), to_signed(16#1E98#, 14), to_signed(16#1E9C#, 14),
     to_signed(16#1E9F#, 14), to_signed(16#1EA3#, 14), to_signed(16#1EA7#, 14), to_signed(16#1EAA#, 14),
     to_signed(16#1EAE#, 14), to_signed(16#1EB1#, 14), to_signed(16#1EB5#, 14), to_signed(16#1EB8#, 14),
     to_signed(16#1EBC#, 14), to_signed(16#1EBF#, 14), to_signed(16#1EC3#, 14), to_signed(16#1EC6#, 14),
     to_signed(16#1ECA#, 14), to_signed(16#1ECD#, 14), to_signed(16#1ED1#, 14), to_signed(16#1ED4#, 14),
     to_signed(16#1ED7#, 14), to_signed(16#1EDB#, 14), to_signed(16#1EDE#, 14), to_signed(16#1EE1#, 14),
     to_signed(16#1EE5#, 14), to_signed(16#1EE8#, 14), to_signed(16#1EEB#, 14), to_signed(16#1EEE#, 14),
     to_signed(16#1EF1#, 14), to_signed(16#1EF5#, 14), to_signed(16#1EF8#, 14), to_signed(16#1EFB#, 14),
     to_signed(16#1EFE#, 14), to_signed(16#1F01#, 14), to_signed(16#1F04#, 14), to_signed(16#1F07#, 14),
     to_signed(16#1F0A#, 14), to_signed(16#1F0E#, 14), to_signed(16#1F11#, 14), to_signed(16#1F14#, 14),
     to_signed(16#1F17#, 14), to_signed(16#1F1A#, 14), to_signed(16#1F1C#, 14), to_signed(16#1F1F#, 14),
     to_signed(16#1F22#, 14), to_signed(16#1F25#, 14), to_signed(16#1F28#, 14), to_signed(16#1F2B#, 14),
     to_signed(16#1F2E#, 14), to_signed(16#1F31#, 14), to_signed(16#1F33#, 14), to_signed(16#1F36#, 14),
     to_signed(16#1F39#, 14), to_signed(16#1F3C#, 14), to_signed(16#1F3E#, 14), to_signed(16#1F41#, 14),
     to_signed(16#1F44#, 14), to_signed(16#1F46#, 14), to_signed(16#1F49#, 14), to_signed(16#1F4C#, 14),
     to_signed(16#1F4E#, 14), to_signed(16#1F51#, 14), to_signed(16#1F54#, 14), to_signed(16#1F56#, 14),
     to_signed(16#1F59#, 14), to_signed(16#1F5B#, 14), to_signed(16#1F5E#, 14), to_signed(16#1F60#, 14),
     to_signed(16#1F63#, 14), to_signed(16#1F65#, 14), to_signed(16#1F67#, 14), to_signed(16#1F6A#, 14),
     to_signed(16#1F6C#, 14), to_signed(16#1F6F#, 14), to_signed(16#1F71#, 14), to_signed(16#1F73#, 14),
     to_signed(16#1F76#, 14), to_signed(16#1F78#, 14), to_signed(16#1F7A#, 14), to_signed(16#1F7C#, 14),
     to_signed(16#1F7F#, 14), to_signed(16#1F81#, 14), to_signed(16#1F83#, 14), to_signed(16#1F85#, 14),
     to_signed(16#1F87#, 14), to_signed(16#1F8A#, 14), to_signed(16#1F8C#, 14), to_signed(16#1F8E#, 14),
     to_signed(16#1F90#, 14), to_signed(16#1F92#, 14), to_signed(16#1F94#, 14), to_signed(16#1F96#, 14),
     to_signed(16#1F98#, 14), to_signed(16#1F9A#, 14), to_signed(16#1F9C#, 14), to_signed(16#1F9E#, 14),
     to_signed(16#1FA0#, 14), to_signed(16#1FA2#, 14), to_signed(16#1FA4#, 14), to_signed(16#1FA5#, 14),
     to_signed(16#1FA7#, 14), to_signed(16#1FA9#, 14), to_signed(16#1FAB#, 14), to_signed(16#1FAD#, 14),
     to_signed(16#1FAF#, 14), to_signed(16#1FB0#, 14), to_signed(16#1FB2#, 14), to_signed(16#1FB4#, 14),
     to_signed(16#1FB5#, 14), to_signed(16#1FB7#, 14), to_signed(16#1FB9#, 14), to_signed(16#1FBA#, 14),
     to_signed(16#1FBC#, 14), to_signed(16#1FBE#, 14), to_signed(16#1FBF#, 14), to_signed(16#1FC1#, 14),
     to_signed(16#1FC2#, 14), to_signed(16#1FC4#, 14), to_signed(16#1FC5#, 14), to_signed(16#1FC7#, 14),
     to_signed(16#1FC8#, 14), to_signed(16#1FCA#, 14), to_signed(16#1FCB#, 14), to_signed(16#1FCD#, 14),
     to_signed(16#1FCE#, 14), to_signed(16#1FCF#, 14), to_signed(16#1FD1#, 14), to_signed(16#1FD2#, 14),
     to_signed(16#1FD3#, 14), to_signed(16#1FD5#, 14), to_signed(16#1FD6#, 14), to_signed(16#1FD7#, 14),
     to_signed(16#1FD9#, 14), to_signed(16#1FDA#, 14), to_signed(16#1FDB#, 14), to_signed(16#1FDC#, 14),
     to_signed(16#1FDD#, 14), to_signed(16#1FDE#, 14), to_signed(16#1FE0#, 14), to_signed(16#1FE1#, 14),
     to_signed(16#1FE2#, 14), to_signed(16#1FE3#, 14), to_signed(16#1FE4#, 14), to_signed(16#1FE5#, 14),
     to_signed(16#1FE6#, 14), to_signed(16#1FE7#, 14), to_signed(16#1FE8#, 14), to_signed(16#1FE9#, 14),
     to_signed(16#1FEA#, 14), to_signed(16#1FEB#, 14), to_signed(16#1FEC#, 14), to_signed(16#1FEC#, 14),
     to_signed(16#1FED#, 14), to_signed(16#1FEE#, 14), to_signed(16#1FEF#, 14), to_signed(16#1FF0#, 14),
     to_signed(16#1FF1#, 14), to_signed(16#1FF1#, 14), to_signed(16#1FF2#, 14), to_signed(16#1FF3#, 14),
     to_signed(16#1FF4#, 14), to_signed(16#1FF4#, 14), to_signed(16#1FF5#, 14), to_signed(16#1FF6#, 14),
     to_signed(16#1FF6#, 14), to_signed(16#1FF7#, 14), to_signed(16#1FF7#, 14), to_signed(16#1FF8#, 14),
     to_signed(16#1FF8#, 14), to_signed(16#1FF9#, 14), to_signed(16#1FF9#, 14), to_signed(16#1FFA#, 14),
     to_signed(16#1FFA#, 14), to_signed(16#1FFB#, 14), to_signed(16#1FFB#, 14), to_signed(16#1FFC#, 14),
     to_signed(16#1FFC#, 14), to_signed(16#1FFD#, 14), to_signed(16#1FFD#, 14), to_signed(16#1FFD#, 14),
     to_signed(16#1FFE#, 14), to_signed(16#1FFE#, 14), to_signed(16#1FFE#, 14), to_signed(16#1FFE#, 14),
     to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14),
     to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14),
     to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14), to_signed(16#1FFF#, 14));  -- sfix14 [1024]
  CONSTANT Lookup_Table2_table_data       : vector_of_unsigned4(0 TO 511) := 
    (to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4), to_unsigned(16#C#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4), to_unsigned(16#C#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4), to_unsigned(16#C#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4), to_unsigned(16#C#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4), to_unsigned(16#C#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4), to_unsigned(16#B#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4), to_unsigned(16#B#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#9#, 4), to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#B#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#8#, 4), to_unsigned(16#9#, 4), to_unsigned(16#A#, 4), to_unsigned(16#A#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#7#, 4),
     to_unsigned(16#8#, 4), to_unsigned(16#9#, 4), to_unsigned(16#9#, 4), to_unsigned(16#A#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#7#, 4),
     to_unsigned(16#8#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4), to_unsigned(16#A#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4),
     to_unsigned(16#8#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4), to_unsigned(16#9#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#5#, 4), to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4),
     to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#5#, 4), to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#6#, 4),
     to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#8#, 4), to_unsigned(16#9#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#6#, 4),
     to_unsigned(16#7#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4), to_unsigned(16#6#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#7#, 4), to_unsigned(16#8#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#7#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#6#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4), to_unsigned(16#7#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#6#, 4), to_unsigned(16#7#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#5#, 4), to_unsigned(16#5#, 4), to_unsigned(16#6#, 4), to_unsigned(16#6#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4), to_unsigned(16#6#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4), to_unsigned(16#5#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#4#, 4), to_unsigned(16#4#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#3#, 4), to_unsigned(16#3#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#2#, 4), to_unsigned(16#2#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4), to_unsigned(16#0#, 4),
     to_unsigned(16#0#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4), to_unsigned(16#1#, 4));  -- ufix4 [512]

  -- Signals
  SIGNAL lutaddr_unsigned                 : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL lutaddrInReg                     : unsigned(13 DOWNTO 0) := to_unsigned(16#0000#, 14);  -- ufix14
  SIGNAL lut1addr                         : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Lookup_Table1_k                  : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL lut1out                          : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL lut2addrp1                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL lut2addrp2                       : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL lut2addr                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Lookup_Table2_k                  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL lut2out                          : unsigned(3 DOWNTO 0);  -- ufix4_En4
  SIGNAL lut1out_reg                      : signed(13 DOWNTO 0) := to_signed(16#0000#, 14);  -- sfix14_En13
  SIGNAL lut2out_reg                      : unsigned(3 DOWNTO 0) := to_unsigned(16#0#, 4);  -- ufix4_En4
  SIGNAL lut2out_extend                   : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL lut2out_sf                       : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL adder_add_cast                   : signed(14 DOWNTO 0);  -- sfix15_En13
  SIGNAL adder_add_cast_1                 : signed(14 DOWNTO 0);  -- sfix15_En13
  SIGNAL adder_add_temp                   : signed(14 DOWNTO 0);  -- sfix15_En13
  SIGNAL addlutouts                       : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL lutoutput_tmp                    : signed(13 DOWNTO 0);  -- sfix14_En13

BEGIN
  lutaddr_unsigned <= unsigned(lutaddr);

  -- Look up table address input register
  LUTaddrRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        lutaddrInReg <= lutaddr_unsigned;
      END IF;
    END IF;
  END PROCESS LUTaddrRegister_process;


  -- Lookup table 1 address
  lut1addr <= lutaddrInReg(13 DOWNTO 4);

  -- Quarter sine wave table-Part1
  
  Lookup_Table1_k <= to_unsigned(16#000#, 10) WHEN lut1addr = to_unsigned(16#000#, 10) ELSE
      to_unsigned(16#3FF#, 10) WHEN lut1addr = to_unsigned(16#3FF#, 10) ELSE
      lut1addr;
  lut1out <= Lookup_Table1_table_data(to_integer(Lookup_Table1_k));

  lut2addrp1 <= lutaddrInReg(13 DOWNTO 9);

  lut2addrp2 <= lutaddrInReg(3 DOWNTO 0);

  -- Lookup table 2 address
  lut2addr <= lut2addrp1 & lut2addrp2;

  -- Quarter Sine Wave Table-Part2
  
  Lookup_Table2_k <= to_unsigned(16#000#, 9) WHEN lut2addr = to_unsigned(16#000#, 9) ELSE
      to_unsigned(16#1FF#, 9) WHEN lut2addr = to_unsigned(16#1FF#, 9) ELSE
      lut2addr;
  lut2out <= Lookup_Table2_table_data(to_integer(Lookup_Table2_k));

  -- Lookup table1 output register
  LUT1outRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        lut1out_reg <= lut1out;
      END IF;
    END IF;
  END PROCESS LUT1outRegister_process;


  -- Lookup table2 output register
  LUT2outRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        lut2out_reg <= lut2out;
      END IF;
    END IF;
  END PROCESS LUT2outRegister_process;


  lut2out_extend <= signed(resize(lut2out_reg & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 14));

  -- Shift look up table 2 outputs
  lut2out_sf <= lut2out_extend srl 9;

  -- Compute look up table output
  adder_add_cast <= resize(lut1out_reg, 15);
  adder_add_cast_1 <= resize(lut2out_sf, 15);
  adder_add_temp <= adder_add_cast + adder_add_cast_1;
  
  addlutouts <= "01111111111111" WHEN (adder_add_temp(14) = '0') AND (adder_add_temp(13) /= '0') ELSE
      "10000000000000" WHEN (adder_add_temp(14) = '1') AND (adder_add_temp(13) /= '1') ELSE
      adder_add_temp(13 DOWNTO 0);

  -- Look up table output register
  LUToutRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      lutoutput_tmp <= to_signed(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        lutoutput_tmp <= addlutouts;
      END IF;
    END IF;
  END PROCESS LUToutRegister_process;


  lutoutput <= std_logic_vector(lutoutput_tmp);

END rtl;

