-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\nco16\nco16.vhd
-- Created: 2021-02-10 22:05:09
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- sin                           ce_out        0.2
-- cos                           ce_out        0.2
-- valid                         ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: nco16
-- Source Path: nco16
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY nco16 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        phase                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        in_valid                          :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        sin                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        cos                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        valid                             :   OUT   std_logic
        );
END nco16;


ARCHITECTURE rtl OF nco16 IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT NCO_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          inc                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          validIn                         :   IN    std_logic;
          sine                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          cosine                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : NCO_HDL_Optimized
    USE ENTITY work.NCO_HDL_Optimized(rtl);

  -- Signals
  SIGNAL NCO_HDL_Optimized_out1           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL NCO_HDL_Optimized_out2           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL NCO_HDL_Optimized_out3           : std_logic;
  SIGNAL NCO_HDL_Optimized_out1_signed    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Data_Type_Conversion_out1        : signed(15 DOWNTO 0);  -- int16
  SIGNAL NCO_HDL_Optimized_out2_signed    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Data_Type_Conversion1_out1       : signed(15 DOWNTO 0);  -- int16

BEGIN
  u_NCO_HDL_Optimized : NCO_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              inc => phase,  -- uint32
              validIn => in_valid,
              sine => NCO_HDL_Optimized_out1,  -- sfix16_En15
              cosine => NCO_HDL_Optimized_out2,  -- sfix16_En15
              validOut => NCO_HDL_Optimized_out3
              );

  NCO_HDL_Optimized_out1_signed <= signed(NCO_HDL_Optimized_out1);

  Data_Type_Conversion_out1 <= NCO_HDL_Optimized_out1_signed;

  sin <= std_logic_vector(Data_Type_Conversion_out1);

  NCO_HDL_Optimized_out2_signed <= signed(NCO_HDL_Optimized_out2);

  Data_Type_Conversion1_out1 <= NCO_HDL_Optimized_out2_signed;

  cos <= std_logic_vector(Data_Type_Conversion1_out1);

  ce_out <= clk_enable;

  valid <= NCO_HDL_Optimized_out3;

END rtl;

