-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\nco14\nco14_WaveformGen.vhd
-- Created: 2021-02-11 22:59:10
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: nco14_WaveformGen
-- Source Path: nco14/NCO HDL Optimized/WaveformGen
-- Hierarchy Level: 2
-- 
-- Wave form Generation Component
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY nco14_WaveformGen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        phaseIdx                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_E16
        sine                              :   OUT   std_logic_vector(13 DOWNTO 0);  -- sfix14_En13
        cosine                            :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En13
        );
END nco14_WaveformGen;


ARCHITECTURE rtl OF nco14_WaveformGen IS

  -- Component Declarations
  COMPONENT nco14_LookUpTableGen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          lutaddr                         :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
          lutoutput                       :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En13
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nco14_LookUpTableGen
    USE ENTITY work.nco14_LookUpTableGen(rtl);

  -- Signals
  SIGNAL phaseIdx_unsigned                : unsigned(15 DOWNTO 0);  -- ufix16_E16
  SIGNAL phaseIdxReg                      : unsigned(15 DOWNTO 0);  -- ufix16_E16
  SIGNAL selsign                          : std_logic;  -- ufix1
  SIGNAL SelsignRegister_reg              : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL selsignreg                       : std_logic;  -- ufix1
  SIGNAL lutaddrexd                       : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL addrOverFsin                     : std_logic;  -- ufix1
  SIGNAL seladdr                          : std_logic;  -- ufix1
  SIGNAL lutaddr1                         : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL lutaddrmax                       : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL lutaddr2                         : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL lutaddrsin                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL AddrOverFsinRegister_reg         : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL addrOverFsinreg                  : std_logic;  -- ufix1
  SIGNAL lutoutsin                        : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL lutoutsin_signed                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL ampOne                           : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL lutoutsin_ampOne                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL uminus_cast                      : signed(14 DOWNTO 0);  -- sfix15_En13
  SIGNAL uminus_cast_1                    : signed(14 DOWNTO 0);  -- sfix15_En13
  SIGNAL lutoutsin_ampOne_inv             : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL sine_tmp                         : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL selsign_cos                      : std_logic;  -- ufix1
  SIGNAL SelsignCosRegister_reg           : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL selsign_cosreg                   : std_logic;  -- ufix1
  SIGNAL addreqzero                       : std_logic;  -- ufix1
  SIGNAL validcnt                         : std_logic;  -- ufix1
  SIGNAL validEnb                         : std_logic;  -- ufix1
  SIGNAL enbreg                           : std_logic;  -- ufix1
  SIGNAL addrOverFcos                     : std_logic;  -- ufix1
  SIGNAL lutaddrcos                       : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL AddrOverFcosRegister_reg         : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL addrOverFcosreg                  : std_logic;  -- ufix1
  SIGNAL lutoutcos                        : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL lutoutcos_signed                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL lutoutcos_ampOne                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL uminus_cast_2                    : signed(14 DOWNTO 0);  -- sfix15_En13
  SIGNAL uminus_cast_3                    : signed(14 DOWNTO 0);  -- sfix15_En13
  SIGNAL lutoutcos_ampOne_inv             : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL cosine_tmp                       : signed(13 DOWNTO 0);  -- sfix14_En13

BEGIN
  u_SineWave_inst : nco14_LookUpTableGen
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              lutaddr => std_logic_vector(lutaddrsin),  -- ufix14
              lutoutput => lutoutsin  -- sfix14_En13
              );

  u_CosineWave_inst : nco14_LookUpTableGen
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              lutaddr => std_logic_vector(lutaddrcos),  -- ufix14
              lutoutput => lutoutcos  -- sfix14_En13
              );

  phaseIdx_unsigned <= unsigned(phaseIdx);

  phaseIdxRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phaseIdxReg <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        phaseIdxReg <= phaseIdx_unsigned;
      END IF;
    END IF;
  END PROCESS phaseIdxRegister_process;


  -- Sine sign selection signal
  selsign <= phaseIdxReg(15);

  SelsignRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      SelsignRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        SelsignRegister_reg(0) <= selsign;
        SelsignRegister_reg(1 TO 2) <= SelsignRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS SelsignRegister_process;

  selsignreg <= SelsignRegister_reg(2);

  -- Get extended LUT address for overflow handling
  lutaddrexd <= phaseIdxReg(14 DOWNTO 0);

  -- Detect sine overflow
  
  addrOverFsin <= '1' WHEN lutaddrexd = to_unsigned(16#4000#, 15) ELSE
      '0';

  seladdr <= phaseIdxReg(14);

  lutaddr1 <= phaseIdxReg(13 DOWNTO 0);

  -- Map LUT address in correct phase
  lutaddrmax <= to_unsigned(16#4000#, 15);

  lutaddr2 <= resize(resize(lutaddrmax, 16) - resize(lutaddr1, 16), 14);

  
  lutaddrsin <= lutaddr1 WHEN seladdr = '0' ELSE
      lutaddr2;

  AddrOverFsinRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      AddrOverFsinRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        AddrOverFsinRegister_reg(0) <= addrOverFsin;
        AddrOverFsinRegister_reg(1 TO 2) <= AddrOverFsinRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS AddrOverFsinRegister_process;

  addrOverFsinreg <= AddrOverFsinRegister_reg(2);

  lutoutsin_signed <= signed(lutoutsin);

  ampOne <= to_signed(16#1FFF#, 14);

  -- Assign sine amplitude One
  
  lutoutsin_ampOne <= lutoutsin_signed WHEN addrOverFsinreg = '0' ELSE
      ampOne;

  uminus_cast <= resize(lutoutsin_ampOne, 15);
  uminus_cast_1 <=  - (uminus_cast);
  lutoutsin_ampOne_inv <= uminus_cast_1(13 DOWNTO 0);

  -- Select sign of Sine output
  
  sine_tmp <= lutoutsin_ampOne WHEN selsignreg = '0' ELSE
      lutoutsin_ampOne_inv;

  sine <= std_logic_vector(sine_tmp);

  -- Cosine sign selection signal
  selsign_cos <= selsign XOR seladdr;

  SelsignCosRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      SelsignCosRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        SelsignCosRegister_reg(0) <= selsign_cos;
        SelsignCosRegister_reg(1 TO 2) <= SelsignCosRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS SelsignCosRegister_process;

  selsign_cosreg <= SelsignCosRegister_reg(2);

  -- Detect cosine overflow
  
  addreqzero <= '1' WHEN lutaddrexd = to_unsigned(16#0000#, 15) ELSE
      '0';

  
  validEnb <= '1' WHEN validcnt < '1' ELSE
      '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 1
  counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validcnt <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND validEnb = '1' THEN
        validcnt <=  NOT validcnt;
      END IF;
    END IF;
  END PROCESS counter_process;


  
  enbreg <= '1' WHEN validcnt = '1' ELSE
      '0';

  addrOverFcos <= addreqzero AND enbreg;

  
  lutaddrcos <= lutaddr2 WHEN seladdr = '0' ELSE
      lutaddr1;

  AddrOverFcosRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      AddrOverFcosRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        AddrOverFcosRegister_reg(0) <= addrOverFcos;
        AddrOverFcosRegister_reg(1 TO 2) <= AddrOverFcosRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS AddrOverFcosRegister_process;

  addrOverFcosreg <= AddrOverFcosRegister_reg(2);

  lutoutcos_signed <= signed(lutoutcos);

  -- Assign cosine amplitude One
  
  lutoutcos_ampOne <= lutoutcos_signed WHEN addrOverFcosreg = '0' ELSE
      ampOne;

  uminus_cast_2 <= resize(lutoutcos_ampOne, 15);
  uminus_cast_3 <=  - (uminus_cast_2);
  lutoutcos_ampOne_inv <= uminus_cast_3(13 DOWNTO 0);

  -- Select sign of cosine output
  
  cosine_tmp <= lutoutcos_ampOne WHEN selsign_cosreg = '0' ELSE
      lutoutcos_ampOne_inv;

  cosine <= std_logic_vector(cosine_tmp);

END rtl;

