-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\nco16\WaveformGen.vhd
-- Created: 2021-02-10 22:05:09
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: WaveformGen
-- Source Path: nco16/NCO HDL Optimized/WaveformGen
-- Hierarchy Level: 2
-- 
-- Wave form Generation Component
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY WaveformGen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        phaseIdx                          :   IN    std_logic_vector(16 DOWNTO 0);  -- ufix17_E15
        sine                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        cosine                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END WaveformGen;


ARCHITECTURE rtl OF WaveformGen IS

  -- Component Declarations
  COMPONENT LookUpTableGen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          lutaddr                         :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
          lutoutput                       :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : LookUpTableGen
    USE ENTITY work.LookUpTableGen(rtl);

  -- Signals
  SIGNAL phaseIdx_unsigned                : unsigned(16 DOWNTO 0);  -- ufix17_E15
  SIGNAL phaseIdxReg                      : unsigned(16 DOWNTO 0);  -- ufix17_E15
  SIGNAL selsign                          : std_logic;  -- ufix1
  SIGNAL SelsignRegister_reg              : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL selsignreg                       : std_logic;  -- ufix1
  SIGNAL lutaddrexd                       : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL addrOverFsin                     : std_logic;  -- ufix1
  SIGNAL seladdr                          : std_logic;  -- ufix1
  SIGNAL lutaddr1                         : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL lutaddrmax                       : unsigned(15 DOWNTO 0);  -- ufix16
  SIGNAL lutaddr2                         : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL lutaddrsin                       : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL AddrOverFsinRegister_reg         : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL addrOverFsinreg                  : std_logic;  -- ufix1
  SIGNAL lutoutsin                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL lutoutsin_signed                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL ampOne                           : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL lutoutsin_ampOne                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL uminus_cast                      : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL uminus_cast_1                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL lutoutsin_ampOne_inv             : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL sine_tmp                         : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL selsign_cos                      : std_logic;  -- ufix1
  SIGNAL SelsignCosRegister_reg           : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL selsign_cosreg                   : std_logic;  -- ufix1
  SIGNAL addreqzero                       : std_logic;  -- ufix1
  SIGNAL validcnt                         : std_logic;  -- ufix1
  SIGNAL validEnb                         : std_logic;  -- ufix1
  SIGNAL enbreg                           : std_logic;  -- ufix1
  SIGNAL addrOverFcos                     : std_logic;  -- ufix1
  SIGNAL lutaddrcos                       : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL AddrOverFcosRegister_reg         : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL addrOverFcosreg                  : std_logic;  -- ufix1
  SIGNAL lutoutcos                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL lutoutcos_signed                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL lutoutcos_ampOne                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL uminus_cast_2                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL uminus_cast_3                    : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL lutoutcos_ampOne_inv             : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL cosine_tmp                       : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  u_SineWave_inst : LookUpTableGen
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              lutaddr => std_logic_vector(lutaddrsin),  -- ufix15
              lutoutput => lutoutsin  -- sfix16_En15
              );

  u_CosineWave_inst : LookUpTableGen
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              lutaddr => std_logic_vector(lutaddrcos),  -- ufix15
              lutoutput => lutoutcos  -- sfix16_En15
              );

  phaseIdx_unsigned <= unsigned(phaseIdx);

  phaseIdxRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phaseIdxReg <= to_unsigned(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        phaseIdxReg <= phaseIdx_unsigned;
      END IF;
    END IF;
  END PROCESS phaseIdxRegister_process;


  -- Sine sign selection signal
  selsign <= phaseIdxReg(16);

  SelsignRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      SelsignRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        SelsignRegister_reg(0) <= selsign;
        SelsignRegister_reg(1 TO 2) <= SelsignRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS SelsignRegister_process;

  selsignreg <= SelsignRegister_reg(2);

  -- Get extended LUT address for overflow handling
  lutaddrexd <= phaseIdxReg(15 DOWNTO 0);

  -- Detect sine overflow
  
  addrOverFsin <= '1' WHEN lutaddrexd = to_unsigned(16#8000#, 16) ELSE
      '0';

  seladdr <= phaseIdxReg(15);

  lutaddr1 <= phaseIdxReg(14 DOWNTO 0);

  -- Map LUT address in correct phase
  lutaddrmax <= to_unsigned(16#8000#, 16);

  lutaddr2 <= resize(resize(lutaddrmax, 17) - resize(lutaddr1, 17), 15);

  
  lutaddrsin <= lutaddr1 WHEN seladdr = '0' ELSE
      lutaddr2;

  AddrOverFsinRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      AddrOverFsinRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        AddrOverFsinRegister_reg(0) <= addrOverFsin;
        AddrOverFsinRegister_reg(1 TO 2) <= AddrOverFsinRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS AddrOverFsinRegister_process;

  addrOverFsinreg <= AddrOverFsinRegister_reg(2);

  lutoutsin_signed <= signed(lutoutsin);

  ampOne <= to_signed(16#7FFF#, 16);

  -- Assign sine amplitude One
  
  lutoutsin_ampOne <= lutoutsin_signed WHEN addrOverFsinreg = '0' ELSE
      ampOne;

  uminus_cast <= resize(lutoutsin_ampOne, 17);
  uminus_cast_1 <=  - (uminus_cast);
  lutoutsin_ampOne_inv <= uminus_cast_1(15 DOWNTO 0);

  -- Select sign of Sine output
  
  sine_tmp <= lutoutsin_ampOne WHEN selsignreg = '0' ELSE
      lutoutsin_ampOne_inv;

  sine <= std_logic_vector(sine_tmp);

  -- Cosine sign selection signal
  selsign_cos <= selsign XOR seladdr;

  SelsignCosRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      SelsignCosRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        SelsignCosRegister_reg(0) <= selsign_cos;
        SelsignCosRegister_reg(1 TO 2) <= SelsignCosRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS SelsignCosRegister_process;

  selsign_cosreg <= SelsignCosRegister_reg(2);

  -- Detect cosine overflow
  
  addreqzero <= '1' WHEN lutaddrexd = to_unsigned(16#0000#, 16) ELSE
      '0';

  
  validEnb <= '1' WHEN validcnt < '1' ELSE
      '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 1
  counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validcnt <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND validEnb = '1' THEN
        validcnt <=  NOT validcnt;
      END IF;
    END IF;
  END PROCESS counter_process;


  
  enbreg <= '1' WHEN validcnt = '1' ELSE
      '0';

  addrOverFcos <= addreqzero AND enbreg;

  
  lutaddrcos <= lutaddr2 WHEN seladdr = '0' ELSE
      lutaddr1;

  AddrOverFcosRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      AddrOverFcosRegister_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        AddrOverFcosRegister_reg(0) <= addrOverFcos;
        AddrOverFcosRegister_reg(1 TO 2) <= AddrOverFcosRegister_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS AddrOverFcosRegister_process;

  addrOverFcosreg <= AddrOverFcosRegister_reg(2);

  lutoutcos_signed <= signed(lutoutcos);

  -- Assign cosine amplitude One
  
  lutoutcos_ampOne <= lutoutcos_signed WHEN addrOverFcosreg = '0' ELSE
      ampOne;

  uminus_cast_2 <= resize(lutoutcos_ampOne, 17);
  uminus_cast_3 <=  - (uminus_cast_2);
  lutoutcos_ampOne_inv <= uminus_cast_3(15 DOWNTO 0);

  -- Select sign of cosine output
  
  cosine_tmp <= lutoutcos_ampOne WHEN selsign_cosreg = '0' ELSE
      lutoutcos_ampOne_inv;

  cosine <= std_logic_vector(cosine_tmp);

END rtl;

